export interface SicCode {
  code: string;
  description: string;
}

export const sicCodes: SicCode[] = [
  { code: "01110", description: "Growing of cereals and other crops" },
  { code: "01210", description: "Farming of cattle, dairy farming" },
  { code: "01410", description: "Raising of dairy cattle" },
  { code: "01420", description: "Raising of other cattle and buffaloes" },
  { code: "01500", description: "Mixed farming" },
  { code: "02100", description: "Silviculture and other forestry activities" },
  { code: "03110", description: "Marine fishing" },
  { code: "05101", description: "Mining of hard coal" },
  { code: "06100", description: "Extraction of crude petroleum" },
  { code: "06200", description: "Extraction of natural gas" },
  { code: "08110", description: "Quarrying of ornamental and building stone" },
  { code: "10110", description: "Processing of meat" },
  { code: "10200", description: "Processing and preserving of fish" },
  { code: "10510", description: "Dairy processing" },
  { code: "10710", description: "Bread and bakery products" },
  { code: "10820", description: "Cocoa and chocolate confectionery" },
  { code: "11010", description: "Distilling alcoholic beverages" },
  { code: "11050", description: "Beer manufacturing" },
  { code: "13100", description: "Textile fibre preparation and spinning" },
  { code: "14110", description: "Manufacture of leather clothes" },
  { code: "14190", description: "Manufacture of other wearing apparel" },
  { code: "15110", description: "Tanning of leather" },
  { code: "16100", description: "Sawmilling and planing of wood" },
  { code: "17120", description: "Manufacture of paper and paperboard" },
  { code: "18110", description: "Printing of newspapers" },
  { code: "18129", description: "Printing (other)" },
  { code: "20110", description: "Manufacture of industrial gases" },
  { code: "20120", description: "Manufacture of dyes and pigments" },
  { code: "20300", description: "Manufacture of paints and coatings" },
  { code: "20420", description: "Manufacture of perfumes and toiletries" },
  { code: "21100", description: "Manufacture of pharmaceutical products" },
  { code: "22110", description: "Manufacture of rubber tyres" },
  { code: "22210", description: "Manufacture of plastic plates and sheets" },
  { code: "22230", description: "Manufacture of plastic products for construction" },
  { code: "23110", description: "Manufacture of flat glass" },
  { code: "23320", description: "Manufacture of bricks and tiles" },
  { code: "24100", description: "Manufacture of basic iron and steel" },
  { code: "24410", description: "Precious metals production" },
  { code: "25110", description: "Manufacture of metal structures" },
  { code: "25620", description: "Machining" },
  { code: "25730", description: "Manufacture of hand tools" },
  { code: "26110", description: "Manufacture of electronic components" },
  { code: "26200", description: "Manufacture of computers" },
  { code: "26301", description: "Manufacture of telegraph equipment" },
  { code: "26400", description: "Manufacture of consumer electronics" },
  { code: "26510", description: "Manufacture of measuring instruments" },
  { code: "26700", description: "Manufacture of optical instruments" },
  { code: "27110", description: "Manufacture of electric motors" },
  { code: "27320", description: "Manufacture of electronic wiring" },
  { code: "27400", description: "Manufacture of electric lighting equipment" },
  { code: "27510", description: "Manufacture of domestic appliances" },
  { code: "28110", description: "Manufacture of engines and turbines" },
  { code: "28220", description: "Manufacture of lifting equipment" },
  { code: "28230", description: "Manufacture of office machinery" },
  { code: "28920", description: "Manufacture of mining machinery" },
  { code: "28930", description: "Manufacture of food processing machinery" },
  { code: "29100", description: "Manufacture of motor vehicles" },
  { code: "29320", description: "Manufacture of motor vehicle parts" },
  { code: "30110", description: "Building of ships" },
  { code: "30200", description: "Manufacture of railway locomotives" },
  { code: "30300", description: "Manufacture of aircraft" },
  { code: "31010", description: "Manufacture of office furniture" },
  { code: "31090", description: "Manufacture of other furniture" },
  { code: "32120", description: "Manufacture of jewellery" },
  { code: "32500", description: "Manufacture of medical instruments" },
  { code: "33110", description: "Repair of fabricated metal products" },
  { code: "33200", description: "Installation of industrial machinery" },
  { code: "35110", description: "Production of electricity" },
  { code: "35210", description: "Manufacture of gas" },
  { code: "36000", description: "Water collection and supply" },
  { code: "37000", description: "Sewerage" },
  { code: "38110", description: "Collection of non-hazardous waste" },
  { code: "38210", description: "Treatment of non-hazardous waste" },
  { code: "38310", description: "Dismantling of wrecks" },
  { code: "39000", description: "Remediation and environmental services" },
  { code: "41100", description: "Development of building projects" },
  { code: "41201", description: "Construction of commercial buildings" },
  { code: "41202", description: "Construction of domestic buildings" },
  { code: "42110", description: "Construction of roads and motorways" },
  { code: "42210", description: "Construction of utility projects" },
  { code: "42990", description: "Construction of other civil engineering projects" },
  { code: "43110", description: "Demolition" },
  { code: "43120", description: "Site preparation" },
  { code: "43210", description: "Electrical installation" },
  { code: "43220", description: "Plumbing, heating and air-conditioning" },
  { code: "43290", description: "Other construction installation" },
  { code: "43310", description: "Plastering" },
  { code: "43320", description: "Joinery installation" },
  { code: "43330", description: "Floor and wall covering" },
  { code: "43341", description: "Painting" },
  { code: "43390", description: "Other building completion" },
  { code: "43991", description: "Scaffolding" },
  { code: "43999", description: "Other specialised construction" },
  { code: "45111", description: "Sale of new cars and light motor vehicles" },
  { code: "45112", description: "Sale of used cars and light motor vehicles" },
  { code: "45200", description: "Maintenance and repair of motor vehicles" },
  { code: "45310", description: "Wholesale of motor vehicle parts" },
  { code: "45320", description: "Retail sale of motor vehicle parts" },
  { code: "45400", description: "Sale and repair of motorcycles" },
  { code: "46110", description: "Wholesale of agricultural raw materials" },
  { code: "46170", description: "Wholesale of food, beverages and tobacco" },
  { code: "46210", description: "Wholesale of grain and seeds" },
  { code: "46310", description: "Wholesale of fruit and vegetables" },
  { code: "46340", description: "Wholesale of beverages" },
  { code: "46390", description: "Non-specialised wholesale of food" },
  { code: "46410", description: "Wholesale of textiles" },
  { code: "46420", description: "Wholesale of clothing and footwear" },
  { code: "46430", description: "Wholesale of electrical household appliances" },
  { code: "46440", description: "Wholesale of china and glassware" },
  { code: "46450", description: "Wholesale of perfume and cosmetics" },
  { code: "46460", description: "Wholesale of pharmaceutical goods" },
  { code: "46470", description: "Wholesale of furniture and carpets" },
  { code: "46510", description: "Wholesale of computers and software" },
  { code: "46520", description: "Wholesale of electronic equipment" },
  { code: "46610", description: "Wholesale of agricultural machinery" },
  { code: "46620", description: "Wholesale of machine tools" },
  { code: "46630", description: "Wholesale of mining and construction machinery" },
  { code: "46690", description: "Wholesale of other machinery and equipment" },
  { code: "46710", description: "Wholesale of fuels" },
  { code: "46720", description: "Wholesale of metals and ores" },
  { code: "46730", description: "Wholesale of wood and construction materials" },
  { code: "46740", description: "Wholesale of hardware and plumbing equipment" },
  { code: "46750", description: "Wholesale of chemical products" },
  { code: "46900", description: "Non-specialised wholesale trade" },
  { code: "47110", description: "Retail in non-specialised stores (food)" },
  { code: "47190", description: "Other retail in non-specialised stores" },
  { code: "47210", description: "Retail of fruit and vegetables" },
  { code: "47220", description: "Retail of meat and meat products" },
  { code: "47230", description: "Retail of fish and seafood" },
  { code: "47240", description: "Retail of bread and confectionery" },
  { code: "47250", description: "Retail of beverages" },
  { code: "47260", description: "Retail of tobacco products" },
  { code: "47291", description: "Retail of dairy products" },
  { code: "47300", description: "Retail of automotive fuel" },
  { code: "47410", description: "Retail of computers and software" },
  { code: "47420", description: "Retail of telecommunications equipment" },
  { code: "47430", description: "Retail of audio and video equipment" },
  { code: "47510", description: "Retail of textiles" },
  { code: "47520", description: "Retail of hardware, paints and glass" },
  { code: "47530", description: "Retail of carpets and rugs" },
  { code: "47540", description: "Retail of electrical household appliances" },
  { code: "47591", description: "Retail of musical instruments" },
  { code: "47599", description: "Retail of furniture and lighting" },
  { code: "47610", description: "Retail of books" },
  { code: "47620", description: "Retail of newspapers and stationery" },
  { code: "47630", description: "Retail of music and video recordings" },
  { code: "47640", description: "Retail of sporting equipment" },
  { code: "47650", description: "Retail of games and toys" },
  { code: "47710", description: "Retail of clothing" },
  { code: "47720", description: "Retail of footwear and leather goods" },
  { code: "47730", description: "Retail of pharmaceutical products" },
  { code: "47740", description: "Retail of medical and orthopaedic goods" },
  { code: "47750", description: "Retail of cosmetics and toiletries" },
  { code: "47760", description: "Retail of flowers, plants and seeds" },
  { code: "47770", description: "Retail of watches and jewellery" },
  { code: "47781", description: "Retail of art and antiques" },
  { code: "47789", description: "Other retail of new goods" },
  { code: "47791", description: "Retail of second-hand goods in stores" },
  { code: "47810", description: "Retail via stalls and markets (food)" },
  { code: "47820", description: "Retail via stalls and markets (textiles)" },
  { code: "47890", description: "Other retail via stalls and markets" },
  { code: "47910", description: "Retail sale via mail order or internet" },
  { code: "47990", description: "Other retail not in stores" },
  { code: "49100", description: "Passenger rail transport" },
  { code: "49200", description: "Freight rail transport" },
  { code: "49311", description: "Urban and suburban passenger transport" },
  { code: "49319", description: "Other passenger land transport" },
  { code: "49320", description: "Taxi operation" },
  { code: "49390", description: "Other passenger land transport n.e.c." },
  { code: "49410", description: "Freight transport by road" },
  { code: "49420", description: "Removal services" },
  { code: "49500", description: "Transport via pipeline" },
  { code: "50100", description: "Sea and coastal passenger transport" },
  { code: "50200", description: "Sea and coastal freight transport" },
  { code: "50300", description: "Inland passenger water transport" },
  { code: "50400", description: "Inland freight water transport" },
  { code: "51100", description: "Passenger air transport" },
  { code: "51210", description: "Freight air transport" },
  { code: "52100", description: "Warehousing and storage" },
  { code: "52211", description: "Operation of rail freight terminals" },
  { code: "52213", description: "Operation of bus and coach stations" },
  { code: "52219", description: "Other service activities related to transport" },
  { code: "52220", description: "Service activities related to water transport" },
  { code: "52230", description: "Service activities related to air transport" },
  { code: "52241", description: "Cargo handling for water transport" },
  { code: "52290", description: "Other transportation support activities" },
  { code: "53100", description: "Postal activities" },
  { code: "53201", description: "Courier activities (licensed)" },
  { code: "53202", description: "Courier activities (unlicensed)" },
  { code: "55100", description: "Hotels and similar accommodation" },
  { code: "55201", description: "Holiday centres and villages" },
  { code: "55202", description: "Youth hostels" },
  { code: "55209", description: "Other short stay accommodation" },
  { code: "55300", description: "Camping grounds and caravan parks" },
  { code: "55900", description: "Other accommodation" },
  { code: "56101", description: "Licensed restaurants" },
  { code: "56102", description: "Unlicensed restaurants and cafes" },
  { code: "56103", description: "Take away food shops" },
  { code: "56210", description: "Event catering activities" },
  { code: "56290", description: "Other food service activities" },
  { code: "56301", description: "Licensed clubs" },
  { code: "56302", description: "Public houses and bars" },
  { code: "58110", description: "Book publishing" },
  { code: "58120", description: "Publishing of directories" },
  { code: "58130", description: "Publishing of newspapers" },
  { code: "58141", description: "Publishing of learned journals" },
  { code: "58142", description: "Publishing of consumer magazines" },
  { code: "58190", description: "Other publishing activities" },
  { code: "58210", description: "Publishing of computer games" },
  { code: "58290", description: "Other software publishing" },
  { code: "59111", description: "Motion picture production" },
  { code: "59112", description: "Video production activities" },
  { code: "59113", description: "Television programme production" },
  { code: "59120", description: "Motion picture and video post-production" },
  { code: "59131", description: "Motion picture distribution" },
  { code: "59140", description: "Motion picture projection" },
  { code: "59200", description: "Sound recording and music publishing" },
  { code: "60100", description: "Radio broadcasting" },
  { code: "60200", description: "Television programming and broadcasting" },
  { code: "61100", description: "Wired telecommunications activities" },
  { code: "61200", description: "Wireless telecommunications activities" },
  { code: "61300", description: "Satellite telecommunications activities" },
  { code: "61900", description: "Other telecommunications activities" },
  { code: "62011", description: "Ready-made interactive leisure software" },
  { code: "62012", description: "Business and domestic software development" },
  { code: "62020", description: "Information technology consultancy" },
  { code: "62030", description: "Computer facilities management" },
  { code: "62090", description: "Other information technology services" },
  { code: "63110", description: "Data processing, hosting and related" },
  { code: "63120", description: "Web portals" },
  { code: "63910", description: "News agency activities" },
  { code: "63990", description: "Other information service activities" },
  { code: "64110", description: "Central banking" },
  { code: "64191", description: "Banks" },
  { code: "64192", description: "Building societies" },
  { code: "64201", description: "Activities of agricultural holding companies" },
  { code: "64205", description: "Activities of financial holding companies" },
  { code: "64209", description: "Activities of other holding companies" },
  { code: "64301", description: "Activities of investment trusts" },
  { code: "64302", description: "Activities of unit trusts" },
  { code: "64303", description: "Activities of venture capital trusts" },
  { code: "64304", description: "Activities of open-ended investment companies" },
  { code: "64305", description: "Activities of property unit trusts" },
  { code: "64306", description: "Activities of real estate investment trusts" },
  { code: "64910", description: "Financial leasing" },
  { code: "64921", description: "Credit granting by credit unions" },
  { code: "64922", description: "Credit granting by building societies" },
  { code: "64929", description: "Other credit granting n.e.c." },
  { code: "64991", description: "Security dealing on own account" },
  { code: "64992", description: "Factoring" },
  { code: "64999", description: "Other financial service activities" },
  { code: "65110", description: "Life insurance" },
  { code: "65120", description: "Non-life insurance" },
  { code: "65201", description: "Life reinsurance" },
  { code: "65202", description: "Non-life reinsurance" },
  { code: "65300", description: "Pension funding" },
  { code: "66110", description: "Administration of financial markets" },
  { code: "66120", description: "Security and commodity contracts dealing" },
  { code: "66190", description: "Other auxiliary financial services" },
  { code: "66210", description: "Risk and damage evaluation" },
  { code: "66220", description: "Activities of insurance agents" },
  { code: "66290", description: "Other activities auxiliary to insurance" },
  { code: "66300", description: "Fund management activities" },
  { code: "68100", description: "Buying and selling of own real estate" },
  { code: "68201", description: "Renting and operating of Housing Association property" },
  { code: "68202", description: "Letting of own property" },
  { code: "68209", description: "Other letting of own property" },
  { code: "68310", description: "Real estate agencies" },
  { code: "68320", description: "Management of real estate on a fee basis" },
  { code: "69101", description: "Barristers" },
  { code: "69102", description: "Solicitors" },
  { code: "69109", description: "Other legal activities n.e.c." },
  { code: "69201", description: "Accounting and auditing activities" },
  { code: "69202", description: "Bookkeeping activities" },
  { code: "69203", description: "Tax consultancy" },
  { code: "70100", description: "Activities of head offices" },
  { code: "70210", description: "Public relations and communications" },
  { code: "70221", description: "Financial management" },
  { code: "70229", description: "Management consultancy (other)" },
  { code: "71111", description: "Architectural activities" },
  { code: "71112", description: "Urban planning and landscape architecture" },
  { code: "71121", description: "Engineering design activities" },
  { code: "71122", description: "Engineering related consultancy" },
  { code: "71129", description: "Other engineering activities n.e.c." },
  { code: "71200", description: "Technical testing and analysis" },
  { code: "72110", description: "Research in biotechnology" },
  { code: "72190", description: "Other natural sciences research" },
  { code: "72200", description: "Social sciences and humanities research" },
  { code: "73110", description: "Advertising agencies" },
  { code: "73120", description: "Media representation services" },
  { code: "73200", description: "Market research and public opinion polling" },
  { code: "74100", description: "Specialised design activities" },
  { code: "74201", description: "Portrait photographic activities" },
  { code: "74202", description: "Other photographic activities" },
  { code: "74203", description: "Film processing" },
  { code: "74209", description: "Other photographic activities n.e.c." },
  { code: "74300", description: "Translation and interpretation" },
  { code: "74901", description: "Environmental consulting" },
  { code: "74902", description: "Quantity surveying" },
  { code: "74909", description: "Other professional activities n.e.c." },
  { code: "75000", description: "Veterinary activities" },
  { code: "77110", description: "Renting of cars and light motor vehicles" },
  { code: "77120", description: "Renting of trucks and heavy vehicles" },
  { code: "77210", description: "Renting of recreational and sports goods" },
  { code: "77220", description: "Renting of video tapes and disks" },
  { code: "77290", description: "Renting of other personal goods" },
  { code: "77310", description: "Renting of agricultural machinery" },
  { code: "77320", description: "Renting of construction machinery" },
  { code: "77330", description: "Renting of office machinery" },
  { code: "77340", description: "Renting of water transport equipment" },
  { code: "77350", description: "Renting of air transport equipment" },
  { code: "77390", description: "Renting of other machinery n.e.c." },
  { code: "77400", description: "Leasing of intellectual property" },
  { code: "78100", description: "Activities of employment placement agencies" },
  { code: "78200", description: "Temporary employment agency activities" },
  { code: "78300", description: "Human resources provision and management" },
  { code: "79110", description: "Travel agency activities" },
  { code: "79120", description: "Tour operator activities" },
  { code: "79901", description: "Tourism information services" },
  { code: "79909", description: "Other reservation services" },
  { code: "80100", description: "Private security activities" },
  { code: "80200", description: "Security systems service activities" },
  { code: "80300", description: "Investigation activities" },
  { code: "81100", description: "Combined facilities support activities" },
  { code: "81210", description: "General cleaning of buildings" },
  { code: "81221", description: "Window cleaning" },
  { code: "81222", description: "Specialised cleaning activities" },
  { code: "81223", description: "Furnace and chimney cleaning" },
  { code: "81229", description: "Other building cleaning activities" },
  { code: "81291", description: "Disinfecting and pest control" },
  { code: "81299", description: "Other cleaning activities n.e.c." },
  { code: "81300", description: "Landscape service activities" },
  { code: "82110", description: "Combined office administrative activities" },
  { code: "82190", description: "Photocopying and document preparation" },
  { code: "82200", description: "Call centre activities" },
  { code: "82301", description: "Convention and trade show organisers" },
  { code: "82302", description: "Activities of conference organisers" },
  { code: "82910", description: "Credit bureaux and collection agencies" },
  { code: "82920", description: "Packaging activities" },
  { code: "82990", description: "Other business support activities n.e.c." },
  { code: "84110", description: "General public administration" },
  { code: "84120", description: "Regulation of health, education, cultural" },
  { code: "84130", description: "Regulation of business activities" },
  { code: "84210", description: "Foreign affairs" },
  { code: "84220", description: "Defence activities" },
  { code: "84230", description: "Justice and judicial activities" },
  { code: "84240", description: "Public order and safety activities" },
  { code: "84250", description: "Fire service activities" },
  { code: "84300", description: "Compulsory social security activities" },
  { code: "85100", description: "Pre-primary education" },
  { code: "85200", description: "Primary education" },
  { code: "85310", description: "General secondary education" },
  { code: "85320", description: "Technical and vocational secondary education" },
  { code: "85410", description: "Post-secondary non-tertiary education" },
  { code: "85421", description: "First-degree level higher education" },
  { code: "85422", description: "Post-graduate level higher education" },
  { code: "85510", description: "Sports and recreation education" },
  { code: "85520", description: "Cultural education" },
  { code: "85530", description: "Driving school activities" },
  { code: "85590", description: "Other education n.e.c." },
  { code: "85600", description: "Educational support activities" },
  { code: "86101", description: "Hospital activities" },
  { code: "86102", description: "Medical nursing home activities" },
  { code: "86210", description: "General medical practice activities" },
  { code: "86220", description: "Specialist medical practice activities" },
  { code: "86230", description: "Dental practice activities" },
  { code: "86900", description: "Other human health activities" },
  { code: "87100", description: "Residential nursing care activities" },
  { code: "87200", description: "Residential care for learning disabilities" },
  { code: "87300", description: "Residential care for the elderly" },
  { code: "87900", description: "Other residential care activities" },
  { code: "88100", description: "Social work without accommodation for elderly" },
  { code: "88910", description: "Child day-care activities" },
  { code: "88990", description: "Other social work activities" },
  { code: "90010", description: "Performing arts" },
  { code: "90020", description: "Support activities to performing arts" },
  { code: "90030", description: "Artistic creation" },
  { code: "90040", description: "Operation of arts facilities" },
  { code: "91011", description: "Library activities" },
  { code: "91012", description: "Archive activities" },
  { code: "91020", description: "Museum activities" },
  { code: "91030", description: "Historical sites and buildings" },
  { code: "91040", description: "Botanical and zoological gardens" },
  { code: "92000", description: "Gambling and betting activities" },
  { code: "93110", description: "Operation of sports facilities" },
  { code: "93120", description: "Activities of sport clubs" },
  { code: "93130", description: "Fitness facilities" },
  { code: "93191", description: "Activities of racehorse owners" },
  { code: "93199", description: "Other sports activities n.e.c." },
  { code: "93210", description: "Activities of amusement parks" },
  { code: "93290", description: "Other amusement and recreation" },
  { code: "94110", description: "Business and employers membership organisations" },
  { code: "94120", description: "Professional membership organisations" },
  { code: "94200", description: "Trade unions" },
  { code: "94910", description: "Activities of religious organisations" },
  { code: "94920", description: "Activities of political organisations" },
  { code: "94990", description: "Activities of other membership organisations" },
  { code: "95110", description: "Repair of computers and peripherals" },
  { code: "95120", description: "Repair of communication equipment" },
  { code: "95210", description: "Repair of consumer electronics" },
  { code: "95220", description: "Repair of household appliances" },
  { code: "95230", description: "Repair of footwear and leather goods" },
  { code: "95240", description: "Repair of furniture and home furnishings" },
  { code: "95250", description: "Repair of watches, clocks and jewellery" },
  { code: "95290", description: "Repair of other personal goods" },
  { code: "96010", description: "Washing and dry-cleaning of textile" },
  { code: "96020", description: "Hairdressing and other beauty treatment" },
  { code: "96030", description: "Funeral and related activities" },
  { code: "96040", description: "Physical well-being activities" },
  { code: "96090", description: "Other personal service activities n.e.c." },
  { code: "97000", description: "Activities of households as employers" },
  { code: "98100", description: "Undifferentiated goods-producing households" },
  { code: "98200", description: "Undifferentiated service-producing households" },
  { code: "99000", description: "Activities of extraterritorial organisations" },
];

export function searchSicCodes(query: string, limit: number = 10): SicCode[] {
  if (!query || query.trim().length === 0) {
    return [];
  }
  
  const lowerQuery = query.toLowerCase().trim();
  
  const results = sicCodes.filter(sic => 
    sic.code.includes(lowerQuery) || 
    sic.description.toLowerCase().includes(lowerQuery)
  );
  
  return results.slice(0, limit);
}
