
import React from 'react';
import { Shield, Lock, FileText, Scale } from 'lucide-react';

interface Props {
  title: string;
}

export const LegalView: React.FC<Props> = ({ title }) => {
  return (
    <div className="max-w-4xl mx-auto px-4 py-20">
      <div className="bg-white border border-gray-200 rounded-[2.5rem] p-12 shadow-sm">
        <div className="flex items-center gap-4 mb-10">
          <div className="w-12 h-12 bg-indigo-50 rounded-xl flex items-center justify-center text-indigo-600">
            {title.includes('Privacy') ? <Lock size={24} /> : <Scale size={24} />}
          </div>
          <div>
            <h1 className="text-3xl font-bold text-gray-900 tracking-tight">{title}</h1>
            <p className="text-gray-400 text-sm">Last Updated: October 2025</p>
          </div>
        </div>

        <div className="prose prose-indigo max-w-none space-y-8 text-gray-600 leading-relaxed">
          <section>
            <h2 className="text-xl font-bold text-gray-900 mb-4 flex items-center gap-2">
              <Shield size={18} className="text-indigo-600" />
              1. Our Professional Commitment
            </h2>
            <p>
              At Pagenti, we operate on a "Digital Placement" model. Unlike typical SaaS products, our Digital Associates are treated as professional services. This means we uphold the highest standards of data integrity and client confidentiality.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-gray-900 mb-4">2. Data Isolation Protocol</h2>
            <p>
              Every Digital Associate (Maya, Oscar, Leo, etc.) operates within a strictly isolated environment. Your company data is never used to train the global model. Our Pagenti Development Engineers ensure that all "learning" remains local to your workspace.
            </p>
          </section>

          <section className="bg-gray-50 p-8 rounded-2xl border border-gray-100">
            <h3 className="font-bold text-gray-900 mb-2">Key Highlights for Compliance:</h3>
            <ul className="list-disc pl-5 space-y-2 text-sm">
              <li>End-to-end encryption for all CRM and Finance API hooks.</li>
              <li>Zero global data sharing between client placements.</li>
              <li>Human-in-the-loop requirement for all sensitive financial operations.</li>
              <li>256-bit AES storage for all audit-ready interaction logs.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-bold text-gray-900 mb-4">3. Placement Terms</h2>
            <p>
              Placement of a Digital Associate is governed by a 12-month service level agreement. Clients retain the right to terminate with 30 days notice. All IP generated by the associate during the placement period belongs exclusively to the client.
            </p>
          </section>
        </div>
      </div>
    </div>
  );
};
