import { useMemo, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { AlertTriangle, CheckCircle2, ClipboardCheck, Download, Eye, FileWarning, LockKeyhole, Plus, RefreshCw, ShieldCheck, Timer } from "lucide-react";
import { apiRequest } from "@/lib/queryClient";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Textarea } from "@/components/ui/textarea";

type PlatformActivity = { id: number; title: string; description?: string | null; activityType?: string | null; priority?: string | null; dueDate?: string | Date | null; completed?: boolean | null; createdAt?: string | Date | null };
const SOURCES = [
  ["SYSC 6 — Compliance monitoring", "https://handbook.fca.org.uk/handbook/sysc6"],
  ["DISP 1 — Complaints and records", "https://handbook.fca.org.uk/handbook/disp1"],
  ["ICO — Data protection principles", "https://ico.org.uk/for-organisations/uk-gdpr-guidance-and-resources/data-protection-principles/a-guide-to-the-data-protection-principles/"],
  ["ICO — DPIAs", "https://ico.org.uk/for-organisations/uk-gdpr-guidance-and-resources/accountability-and-governance/data-protection-impact-assessments-dpias/"],
] as const;
const dateOf = (value?: string | Date | null) => { if (!value) return null; const date = new Date(value); return Number.isNaN(date.getTime()) ? null : date; };

export function ComplianceOfficer() {
  const queryClient = useQueryClient();
  const [incident, setIncident] = useState("");
  const { data: activities = [], isLoading, isFetching, refetch } = useQuery<PlatformActivity[]>({ queryKey: ["/api/activities"], queryFn: async () => { const response = await fetch("/api/activities"); if (!response.ok) throw new Error("Could not load platform activity"); return response.json(); } });
  const now = new Date();
  const recent = useMemo(() => activities.filter(a => { const created = dateOf(a.createdAt); return !created || now.getTime() - created.getTime() <= 30 * 86400000; }), [activities]);
  const overdue = useMemo(() => activities.filter(a => { const due = dateOf(a.dueDate); return Boolean(due && due < now && !a.completed); }), [activities]);
  const recordIncident = useMutation({ mutationFn: () => apiRequest("/api/activities", "POST", { title: "Compliance Officer incident raised", description: incident.trim(), activityType: "compliance_incident", priority: "high", completed: false }), onSuccess: () => { setIncident(""); queryClient.invalidateQueries({ queryKey: ["/api/activities"] }); } });
  const exportRegister = () => { const blob = new Blob([JSON.stringify({ generatedAt: new Date().toISOString(), observationWindow: "30 days", activities, overdueCount: overdue.length, note: "Operational monitoring export; final regulatory decisions remain subject to Compliance Officer review." }, null, 2)], { type: "application/json" }); const url = URL.createObjectURL(blob); const link = document.createElement("a"); link.href = url; link.download = `strata-compliance-register-${new Date().toISOString().slice(0, 10)}.json`; link.click(); URL.revokeObjectURL(url); };
  const controls = [
    ["Operational activity capture", `${recent.length} activities observed in the last 30 days`, recent.length > 0, Eye],
    ["Open actions and exceptions", overdue.length ? `${overdue.length} overdue action${overdue.length === 1 ? "" : "s"} require review` : "No overdue actions detected", overdue.length === 0, Timer],
    ["Complaints and incident register", "Record, classify, investigate and evidence resolution", false, FileWarning],
    ["Client-file evidence", "Evidence checks require a linked prospect/file control", false, ClipboardCheck],
  ] as const;
  const gdprControls = ["Lawful basis and transparency", "Purpose limitation and minimisation", "Accuracy and data quality", "Retention and secure disposal", "Rights requests", "Security and data breaches", "DPIA and processor oversight"];
  return <div className="space-y-5 pb-6">
    <Card className="border-primary/20 bg-gradient-to-br from-primary/10 via-card to-card"><CardContent className="p-5"><div className="flex flex-col gap-4 lg:flex-row lg:items-start lg:justify-between"><div className="flex gap-3"><div className="rounded-xl bg-primary/15 p-3 text-primary"><ShieldCheck className="h-6 w-6" /></div><div><div className="flex flex-wrap items-center gap-2"><h2 className="text-lg font-bold">Compliance Officer</h2><Badge className="bg-emerald-500/15 text-emerald-400 hover:bg-emerald-500/15"><span className="mr-1.5 inline-block h-1.5 w-1.5 rounded-full bg-emerald-400" />Monitoring</Badge></div><p className="mt-1 max-w-2xl text-xs leading-relaxed text-muted-foreground">Observes Nexus activity, identifies control exceptions, preserves the compliance register, and gives Strata a review queue for FCA and UK GDPR obligations.</p></div></div><div className="flex gap-2"><Button variant="outline" size="sm" onClick={() => refetch()} disabled={isFetching}><RefreshCw className={`mr-2 h-3.5 w-3.5 ${isFetching ? "animate-spin" : ""}`} />Refresh</Button><Button size="sm" onClick={exportRegister}><Download className="mr-2 h-3.5 w-3.5" />Export register</Button></div></div></CardContent></Card>
    <div className="grid grid-cols-2 gap-3 lg:grid-cols-4"><Metric label="Control posture" value="Amber" Icon={AlertTriangle} tone="text-amber-400" /><Metric label="Observed (30 days)" value={recent.length} Icon={Eye} tone="text-blue-400" /><Metric label="Open exceptions" value={overdue.length} Icon={AlertTriangle} tone={overdue.length ? "text-rose-400" : "text-emerald-400"} /><Metric label="Register entries" value={activities.length} Icon={LockKeyhole} tone="text-violet-400" /></div>
    <div className="grid gap-5 xl:grid-cols-[1.15fr_.85fr]"><Card><CardHeader className="pb-3"><CardTitle className="text-sm">Control monitoring</CardTitle><CardDescription className="text-xs">Each control has an observable signal and an accountable follow-up.</CardDescription></CardHeader><CardContent className="space-y-2">{controls.map(([name, detail, ok, Icon]) => <div key={name} className="flex items-start gap-3 rounded-lg border border-border/60 p-3"><Icon className={`mt-0.5 h-4 w-4 shrink-0 ${ok ? "text-emerald-400" : "text-amber-400"}`} /><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center justify-between gap-2"><p className="text-xs font-semibold">{name}</p><Badge variant="outline" className={`text-[9px] ${ok ? "border-emerald-500/30 text-emerald-400" : "border-amber-500/30 text-amber-400"}`}>{ok ? "Observed" : "Review required"}</Badge></div><p className="mt-1 text-[11px] text-muted-foreground">{detail}</p></div></div>)}</CardContent></Card><Card><CardHeader className="pb-3"><CardTitle className="text-sm">Raise an incident or exception</CardTitle><CardDescription className="text-xs">Record facts first; classification, ownership, remediation and reporting decisions follow review.</CardDescription></CardHeader><CardContent className="space-y-3"><Textarea value={incident} onChange={e => setIncident(e.target.value)} placeholder="What happened, when, who or what was affected, and what evidence exists?" className="min-h-[108px] text-xs" /><Button className="w-full" disabled={!incident.trim() || recordIncident.isPending} onClick={() => recordIncident.mutate()}><Plus className="mr-2 h-3.5 w-3.5" />Record in compliance register</Button></CardContent></Card></div>
    <Card className="border-cyan-500/20"><CardHeader className="pb-3"><div className="flex items-start justify-between gap-2"><div><CardTitle className="text-sm">UK GDPR control register</CardTitle><CardDescription className="text-xs">Privacy evidence is monitored as an operational control, not just a policy document.</CardDescription></div><Badge variant="outline" className="border-amber-500/30 text-[9px] text-amber-400">Evidence required</Badge></div></CardHeader><CardContent className="grid gap-2 md:grid-cols-2 xl:grid-cols-4">{gdprControls.map(name => <div key={name} className="rounded-lg border border-border/60 p-3"><div className="flex items-start gap-2"><LockKeyhole className="mt-0.5 h-3.5 w-3.5 shrink-0 text-cyan-400" /><p className="text-[11px] font-semibold">{name}</p></div><Badge variant="outline" className="mt-2 border-amber-500/30 text-[9px] text-amber-400">Needs evidence</Badge></div>)}</CardContent></Card>
    <Card><CardHeader className="flex-row items-center justify-between space-y-0 pb-3"><div><CardTitle className="text-sm">Observed platform activity</CardTitle><CardDescription className="text-xs">Authenticated activity feed used by the officer’s monitoring pass.</CardDescription></div><Badge variant="outline" className="text-[9px]">{isLoading ? "Loading…" : `${activities.length} total`}</Badge></CardHeader><CardContent>{activities.length === 0 ? <p className="py-6 text-center text-xs text-muted-foreground">No activity has been captured yet. The officer cannot evidence what the platform has not recorded.</p> : <div className="space-y-2">{activities.slice(0, 8).map(a => <div key={a.id} className="flex items-start justify-between gap-3 border-b border-border/50 py-2 last:border-0"><div className="min-w-0"><p className="truncate text-xs font-medium">{a.title}</p><p className="mt-0.5 truncate text-[10px] text-muted-foreground">{a.description || a.activityType || "Platform activity"}</p></div><Badge variant="outline" className="shrink-0 text-[9px]">{a.completed ? "Complete" : a.priority || "Open"}</Badge></div>)}</div>}</CardContent></Card>
    <Card className="border-muted-foreground/20"><CardHeader className="pb-3"><CardTitle className="text-sm">Regulatory anchors</CardTitle><CardDescription className="text-xs">Review current FCA and ICO source material before making a reporting or privacy decision.</CardDescription></CardHeader><CardContent className="flex flex-wrap gap-2">{SOURCES.map(([label, href]) => <a key={href} href={href} target="_blank" rel="noreferrer" className="rounded-md border border-border px-3 py-2 text-[11px] text-primary hover:bg-muted">{label}</a>)}</CardContent></Card>
  </div>;
}
function Metric({ label, value, Icon, tone }: { label: string; value: string | number; Icon: typeof Eye; tone: string }) { return <Card><CardContent className="flex items-center gap-3 p-4"><Icon className={`h-5 w-5 ${tone}`} /><div><p className="text-[9px] uppercase tracking-wider text-muted-foreground">{label}</p><p className={`mt-1 text-xl font-bold ${tone}`}>{value}</p></div></CardContent></Card>; }
