CREATE TABLE `activities` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`user_id` text NOT NULL,
	`prospect_id` integer,
	`title` text NOT NULL,
	`description` text,
	`activity_type` text DEFAULT 'task',
	`priority` text DEFAULT 'medium',
	`due_date` integer,
	`completed` integer DEFAULT false,
	`created_at` integer DEFAULT CURRENT_TIMESTAMP,
	`updated_at` integer DEFAULT CURRENT_TIMESTAMP
);
--> statement-breakpoint
CREATE TABLE `broker_leads` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`company_name` text NOT NULL,
	`company_number` text,
	`contact_name` text,
	`email` text,
	`phone` text,
	`status` text DEFAULT 'new',
	`assigned_agent_id` text,
	`notes` text,
	`source` text,
	`contacts` text,
	`created_at` integer DEFAULT CURRENT_TIMESTAMP,
	`updated_at` integer DEFAULT CURRENT_TIMESTAMP
);
--> statement-breakpoint
CREATE TABLE `cdfis` (
	`id` text PRIMARY KEY NOT NULL,
	`user_id` text NOT NULL,
	`name` text NOT NULL,
	`website` text,
	`contact_name` text,
	`contact_phone` text,
	`contact_email` text,
	`postal_address` text,
	`lending_min_quantum` integer,
	`lending_max_quantum` integer,
	`geographical_scope` text,
	`preferred_client_types` text,
	`background_info` text,
	`last_contacted` integer,
	`contact_outcome` text DEFAULT 'not_contacted',
	`agreement_status` text DEFAULT 'unsigned',
	`agreement_signed_date` integer,
	`notes` text,
	`created_at` integer DEFAULT CURRENT_TIMESTAMP,
	`updated_at` integer DEFAULT CURRENT_TIMESTAMP
);
--> statement-breakpoint
CREATE TABLE `companies` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`company_name` text NOT NULL,
	`company_number` text NOT NULL,
	`registered_address` text,
	`postcode` text,
	`incorporation_date` text,
	`company_status` text,
	`company_type` text,
	`website` text,
	`sic_code` text,
	`sic_description` text,
	`created_at` integer DEFAULT CURRENT_TIMESTAMP
);
--> statement-breakpoint
CREATE TABLE `contacts` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`prospect_id` integer NOT NULL,
	`name` text NOT NULL,
	`email` text,
	`phone` text,
	`role` text,
	`is_primary` integer DEFAULT false,
	`profile_picture` text,
	`notes` text,
	`created_at` integer DEFAULT CURRENT_TIMESTAMP
);
--> statement-breakpoint
CREATE TABLE `email_templates` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`user_id` text NOT NULL,
	`name` text NOT NULL,
	`subject` text NOT NULL,
	`content` text NOT NULL,
	`category` text,
	`is_global` integer DEFAULT false,
	`created_at` integer DEFAULT CURRENT_TIMESTAMP,
	`updated_at` integer DEFAULT CURRENT_TIMESTAMP
);
--> statement-breakpoint
CREATE TABLE `internal_leads` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`company_name` text NOT NULL,
	`company_number` text,
	`contact_name` text,
	`email` text,
	`phone` text,
	`status` text DEFAULT 'new',
	`assigned_agent_id` text,
	`commission_rate` real DEFAULT 0.1,
	`notes` text,
	`estimated_value` integer,
	`address` text,
	`city` text,
	`has_charges` integer DEFAULT false,
	`identified_lender` text,
	`charge_date` text,
	`charge_amount` integer,
	`charge_status` text,
	`total_charges_count` integer DEFAULT 0,
	`satisfied_charges_count` integer DEFAULT 0,
	`company_type` text,
	`sic_code` text,
	`incorporation_date` text,
	`website` text,
	`linkedin_url` text,
	`contacts` text,
	`possible_duplicate` integer DEFAULT false,
	`created_at` integer DEFAULT CURRENT_TIMESTAMP,
	`updated_at` integer DEFAULT CURRENT_TIMESTAMP
);
--> statement-breakpoint
CREATE TABLE `lenders` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`user_id` text NOT NULL,
	`institution_name` text NOT NULL,
	`contact_name` text,
	`email` text NOT NULL,
	`phone` text,
	`address` text,
	`website` text,
	`notes` text,
	`lender_type` text DEFAULT 'bank',
	`logo_url` text,
	`is_global` integer DEFAULT 0,
	`product_types` text,
	`min_loan_amount` integer,
	`max_loan_amount` integer,
	`min_term_months` integer,
	`max_term_months` integer,
	`min_ltv` real,
	`max_ltv` real,
	`linkedin_url` text,
	`portal_url` text,
	`typical_rate_from` text,
	`typical_rate_to` text,
	`arrangement_fee` text,
	`sectors` text,
	`regions` text,
	`security_types` text,
	`borrower_types` text,
	`min_trading_years` integer,
	`min_revenue` integer,
	`min_dscr` text,
	`accepts_startups` integer DEFAULT 0,
	`turnaround_days` integer,
	`panel_status` text DEFAULT 'market',
	`accreditation_status` text,
	`fca_reference` text,
	`accreditation_expiry` integer,
	`bdm_name` text,
	`bdm_email` text,
	`bdm_phone` text,
	`underwriter_email` text,
	`submission_email` text,
	`processing_notes` text,
	`credit_appetite` text,
	`key_strengths` text,
	`key_weaknesses` text,
	`rating` real,
	`is_favourite` integer DEFAULT 0,
	`introducer_agreement_signed` integer DEFAULT 0,
	`lending_policy` text,
	`insights` text,
	`tier` real,
	`last_contacted_at` integer,
	`created_at` integer DEFAULT CURRENT_TIMESTAMP,
	`updated_at` integer DEFAULT CURRENT_TIMESTAMP
);
--> statement-breakpoint
CREATE TABLE `marketing_contacts` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`user_id` text NOT NULL,
	`first_name` text,
	`last_name` text,
	`email` text NOT NULL,
	`phone` text,
	`company` text,
	`job_title` text,
	`status` text DEFAULT 'active',
	`lifecycle_stage` text DEFAULT 'lead',
	`lead_source` text,
	`tags` text,
	`notes` text,
	`last_contacted_at` integer,
	`unsubscribed` integer DEFAULT false,
	`created_at` integer DEFAULT CURRENT_TIMESTAMP,
	`updated_at` integer DEFAULT CURRENT_TIMESTAMP
);
--> statement-breakpoint
CREATE TABLE `prospects` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`user_id` text NOT NULL,
	`team_id` integer,
	`company_id` integer NOT NULL,
	`stage` text DEFAULT 'lead',
	`loan_amount` integer,
	`term` integer,
	`interest_rate` text,
	`directors_guarantee` integer DEFAULT 0,
	`commercial_property` integer DEFAULT 0,
	`home_equity` integer DEFAULT 0,
	`property_other` integer DEFAULT 0,
	`debenture` integer DEFAULT 0,
	`parent_company_guarantee` integer DEFAULT 0,
	`collateral` integer DEFAULT 0,
	`cross_company_guarantee` integer DEFAULT 0,
	`loan_requirement_notes` text,
	`loan_allocation` text,
	`priority` text,
	`notes` text,
	`saved_associations` text,
	`queue_order` integer DEFAULT 0,
	`referral_source` text,
	`background` text,
	`adviser_recommendation` text,
	`adviser_recommendation_signed_by` text,
	`adviser_recommendation_signed_at` integer,
	`loan_requirement_data` text,
	`research_data` text,
	`created_at` integer DEFAULT CURRENT_TIMESTAMP,
	`updated_at` integer DEFAULT CURRENT_TIMESTAMP
);
--> statement-breakpoint
CREATE TABLE `scraped_leads` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`company_name` text NOT NULL,
	`company_number` text NOT NULL,
	`email` text,
	`website` text,
	`phone` text,
	`address` text,
	`status` text DEFAULT 'new',
	`created_at` integer DEFAULT CURRENT_TIMESTAMP,
	`updated_at` integer DEFAULT CURRENT_TIMESTAMP
);
--> statement-breakpoint
CREATE TABLE `system_settings` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`key` text NOT NULL,
	`value` text NOT NULL,
	`updated_by` text,
	`updated_at` integer DEFAULT CURRENT_TIMESTAMP
);
--> statement-breakpoint
CREATE UNIQUE INDEX `system_settings_key_unique` ON `system_settings` (`key`);--> statement-breakpoint
CREATE TABLE `users` (
	`id` text PRIMARY KEY NOT NULL,
	`email` text,
	`password` text NOT NULL,
	`first_name` text,
	`last_name` text,
	`profile_image_url` text,
	`role` text DEFAULT 'broker',
	`subscription_tier` text DEFAULT 'free',
	`prospect_limit` integer DEFAULT 10,
	`gocardless_customer_id` text,
	`gocardless_mandate_id` text,
	`gocardless_subscription_id` text,
	`stripe_customer_id` text,
	`stripe_subscription_id` text,
	`trial_ends_at` integer,
	`trial_tier` text,
	`currency` text DEFAULT 'GBP',
	`timezone` text DEFAULT 'Europe/London',
	`date_format` text DEFAULT 'DD/MM/YYYY',
	`theme` text DEFAULT 'light',
	`pipeline_stage_names` text,
	`pdf_layout_preferences` text,
	`branding_logo_url` text,
	`branding_primary_color` text,
	`branding_accent_color` text,
	`branding_sidebar_color` text,
	`branding_background_color` text,
	`webhook_api_key_hash` text,
	`webhook_api_key_suffix` text,
	`webhook_api_key_created_at` integer,
	`webhook_api_key_last_used_at` integer,
	`ai_data_consent` integer DEFAULT 0,
	`ai_data_consent_at` integer,
	`has_underwriting_access` integer DEFAULT 0,
	`underwriting_access_expires_at` integer,
	`created_at` integer DEFAULT CURRENT_TIMESTAMP,
	`updated_at` integer DEFAULT CURRENT_TIMESTAMP,
	`last_login_at` integer,
	`last_logout_at` integer,
	`prospects_created_count` integer DEFAULT 0,
	`onboarding_enabled` integer DEFAULT 1,
	`onboarding_progress` text,
	`suspended` integer DEFAULT false,
	`google_connected` integer DEFAULT false,
	`google_email` text,
	`google_access_token` text,
	`google_refresh_token` text,
	`google_token_expiry` integer
);
