import { useMemo, useState } from "react";
import { useLocation } from "wouter";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Slider } from "@/components/ui/slider";
import logo from "@assets/logo-chrome.png";
import { ArrowRight, Check, CheckCircle2, ChevronDown, Clock3, Code2, Menu, PoundSterling, ShieldCheck, Sparkles, Target, Users, X } from "lucide-react";

const nav = [{ l: "What we build", h: "#services" }, { l: "Proof", h: "#results" }, { l: "Process", h: "#process" }, { l: "Investment", h: "#pricing" }];
const services = [{ i: Clock3, t: "Remove the drag", b: "Automate repetitive work that steals good people from higher-value decisions." }, { i: PoundSterling, t: "Make margin visible", b: "Connect the moving parts so you can see where time, money and momentum are leaking." }, { i: Target, t: "Turn interest into action", b: "Build a faster path from enquiry to follow-up, with fewer leads falling through the gaps." }, { i: Users, t: "Give your team leverage", b: "Software that fits the way your business actually works — and gets used after launch." }];
const proofs = [{ tag: "COMMERCIAL FINANCE", title: "From spreadsheet sprawl to one clear operating system.", body: "Manage prospects, applications, lender matching and follow-up in one place.", m: "60%+", ml: "less admin time" }, { tag: "REGULATED TEAMS", title: "Compliance that keeps pace with the business.", body: "Surface gaps, track changes and generate audit-ready reporting without the annual scramble.", m: "80%", ml: "faster reviews" }, { tag: "SALES OPERATIONS", title: "More of the right leads. Less of the wrong work.", body: "Identify, qualify and prioritise prospects so your team spends more time in useful conversations.", m: "3×", ml: "more qualified leads" }];
const steps = [{ n: "01", t: "Find the friction", b: "Understand what slows the business down and where the upside is." }, { n: "02", t: "Scope the win", b: "A clear proposal with the workflow, investment and intended result." }, { n: "03", t: "Build in the open", b: "Working software, visible progress and regular check-ins." }, { n: "04", t: "Make it stick", b: "Launch with your team, train the people using it and stay close." }];
const plans = [{ t: "Quick Win", p: "From £500", s: "One purpose-built system to automate any ONE aspect of your business on autopilot.", b: ["One focused outcome", "Handover and training", "30 days support"] }, { t: "Multi-Tasker", p: "From £1,500", s: "A bespoke Operating System built specifically for multiple areas of your business.", b: ["Connected workflows", "Custom dashboard", "90 days support"] }, { t: "Game Changer", p: "POA", s: "A fully localised AI Operating System to futureproof your business.", b: ["End-to-end development", "Localised AI workflows", "Scale with the business"] }];

export default function LandingV2() {
  const [, go] = useLocation(); const [open, setOpen] = useState(false); const [hours, setHours] = useState([20]); const [rate, setRate] = useState([50]); const [email, setEmail] = useState(""); const [name, setName] = useState(""); const [company, setCompany] = useState(""); const [sent, setSent] = useState(false); const [sending, setSending] = useState(false);
  const roi = useMemo(() => { const cost = hours[0] * rate[0] * 52; return { cost, save: cost * .7, time: hours[0] * .7 * 4.33 }; }, [hours, rate]);
  const scroll = (id: string) => { setOpen(false); document.querySelector(id)?.scrollIntoView({ behavior: "smooth" }); };
  const submit = async (e: React.FormEvent) => { e.preventDefault(); setSending(true); try { const r = await fetch("/api/marketing/waitlist", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ email, firstName: name, companyName: company, source: "landing-redesign" }) }); if (r.ok || r.status === 409) setSent(true); } finally { setSending(false); } };
  return <div className="veltro-site min-h-screen overflow-hidden bg-[#0b1010] text-[#f2f6ef] selection:bg-[#b9f35a] selection:text-[#10150d]">
    <header className="fixed inset-x-0 top-0 z-50 border-b border-white/[.08] bg-[#0b1010]/80 backdrop-blur-xl"><div className="mx-auto flex max-w-7xl items-center justify-between px-5 py-4 lg:px-8"><button onClick={() => scroll("#top")}><img src={logo} alt="Veltro" className="h-8 w-auto" /></button><nav className="hidden gap-8 md:flex">{nav.map(x => <button key={x.h} onClick={() => scroll(x.h)} className="text-sm text-[#a9b2ad] hover:text-[#b9f35a]">{x.l}</button>)}</nav><div className="flex items-center gap-3"><button onClick={() => go("/auth")} className="hidden text-sm text-[#a9b2ad] hover:text-white sm:block">Log in</button><Button onClick={() => scroll("#contact")} className="hidden rounded-full bg-[#b9f35a] px-5 font-semibold text-[#11170d] hover:bg-[#d4ff8b] sm:inline-flex">Start a conversation <ArrowRight className="ml-2 h-4 w-4" /></Button><button onClick={() => setOpen(!open)} className="rounded-full border border-white/10 p-2 md:hidden" aria-label="Menu">{open ? <X className="h-5 w-5" /> : <Menu className="h-5 w-5" />}</button></div></div>{open && <div className="border-t border-white/10 bg-[#0b1010] px-5 py-4 md:hidden">{nav.map(x => <button key={x.h} onClick={() => scroll(x.h)} className="block w-full py-3 text-left">{x.l}</button>)}</div>}</header>
    <main id="top">
      <section className="relative isolate flex min-h-[760px] items-center border-b border-white/[.08] px-5 pb-20 pt-36 lg:px-8"><div className="hero-grid absolute inset-0 -z-10 opacity-60" /><div className="absolute -right-32 top-24 -z-10 h-[460px] w-[460px] rounded-full bg-[#b9f35a]/[.12] blur-[110px]" /><div className="mx-auto grid w-full max-w-7xl items-center gap-16 lg:grid-cols-[1.1fr_.9fr]"><div><div className="eyebrow mb-8 flex items-center gap-3"><span className="h-px w-8 bg-[#b9f35a]" /> Forward development engineering</div><h1 className="max-w-4xl text-[clamp(3.5rem,8vw,7.8rem)] font-semibold leading-[.88] tracking-[-.07em]">Make the <span className="text-[#b9f35a]">hard parts</span> of business easier.</h1><p className="mt-8 max-w-xl text-lg leading-relaxed text-[#a9b2ad]">Veltro builds the practical software your business needs next — to cut admin, protect margin and help good teams move faster.</p><div className="mt-10 flex flex-col gap-3 sm:flex-row"><Button onClick={() => scroll("#contact")} className="h-14 rounded-full bg-[#b9f35a] px-7 text-base font-semibold text-[#11170d] hover:bg-[#d4ff8b]">Tell us where it hurts <ArrowRight className="ml-2 h-5 w-5" /></Button><Button variant="ghost" onClick={() => scroll("#results")} className="h-14 rounded-full px-7 text-base text-[#d2dad4] hover:bg-white/5">See what changed <ChevronDown className="ml-2 h-4 w-4" /></Button></div><div className="mt-12 flex gap-8 text-xs uppercase tracking-[.16em] text-[#718079]"><span className="flex items-center gap-2"><ShieldCheck className="h-4 w-4 text-[#b9f35a]" /> Real teams</span><span className="flex items-center gap-2"><Code2 className="h-4 w-4 text-[#b9f35a]" /> No black boxes</span></div></div><div className="relative hidden min-h-[470px] lg:block"><div className="absolute right-6 top-12 w-[390px] rotate-[-5deg] rounded-2xl border border-white/10 bg-[#161f1d]/90 p-5 shadow-2xl"><div className="mb-8 flex justify-between text-xs text-[#9daaa1]"><span>Veltro / Operations</span><span className="rounded-full bg-[#b9f35a]/15 px-2 py-1 text-[#b9f35a]">LIVE</span></div><div className="text-xs text-[#78847d]">TIME RECOVERED THIS MONTH</div><div className="mt-1 text-5xl font-semibold">61.4<span className="ml-2 text-lg text-[#b9f35a]">hrs</span></div><div className="mt-8 flex h-24 items-end gap-2">{[35,44,38,58,50,74,68,92,84,100].map((h, i) => <div key={i} style={{ height: `${h}%` }} className={`flex-1 rounded-t-sm ${i > 6 ? "bg-[#b9f35a]" : "bg-[#3d5545]"}`} />)}</div></div><div className="absolute bottom-16 left-0 w-[260px] rounded-2xl border border-white/10 bg-[#101716] p-5 shadow-2xl"><div className="mb-7 flex items-center gap-3"><div className="rounded-lg bg-[#b9f35a]/15 p-2"><Sparkles className="h-4 w-4 text-[#b9f35a]" /></div><span className="text-sm">Next best action</span></div><p className="text-sm text-[#a9b2ad]">Follow up with <span className="text-white">8 warm leads</span> before 4pm.</p></div></div></div></section>
      <section id="services" className="mx-auto max-w-7xl px-5 py-24 lg:px-8 lg:py-32"><div className="grid gap-12 lg:grid-cols-[.7fr_1.3fr]"><div><p className="eyebrow">The point of the work</p><h2 className="mt-5 max-w-sm text-4xl font-semibold leading-tight tracking-[-.05em] lg:text-5xl">Software should earn its place.</h2></div><div className="grid gap-px overflow-hidden rounded-2xl border border-white/10 bg-white/10 sm:grid-cols-2">{services.map(x => <div key={x.t} className="bg-[#111918] p-7 hover:bg-[#18221f]"><x.i className="h-6 w-6 text-[#b9f35a]" /><h3 className="mt-12 text-xl">{x.t}</h3><p className="mt-3 text-sm leading-relaxed text-[#89958e]">{x.b}</p></div>)}</div></div></section>
      <section id="savings" className="border-y border-white/[.08] bg-[#101716] px-5 py-24 lg:px-8 lg:py-32"><div className="mx-auto grid max-w-7xl gap-14 lg:grid-cols-[.8fr_1.2fr] lg:items-center"><div><p className="eyebrow">A useful first number</p><h2 className="mt-5 max-w-lg text-4xl font-semibold leading-tight tracking-[-.05em] lg:text-6xl">What is busy work costing you?</h2><p className="mt-6 max-w-md leading-relaxed text-[#89958e]">Use the sliders for a quick, conservative estimate. We assume 70% of repetitive work can be automated.</p></div><div className="rounded-2xl border border-white/10 bg-[#0b1010] p-6 md:p-10"><div className="grid gap-10 md:grid-cols-2"><div className="space-y-9"><div><div className="mb-3 flex justify-between text-sm"><span>Hours lost each week</span><span className="text-[#b9f35a]">{hours[0]}h</span></div><Slider value={hours} onValueChange={setHours} min={5} max={80} step={5} /></div><div><div className="mb-3 flex justify-between text-sm"><span>Blended hourly cost</span><span className="text-[#b9f35a]">£{rate[0]}</span></div><Slider value={rate} onValueChange={setRate} min={15} max={150} step={5} /></div></div><div className="border-t border-white/10 pt-8 md:border-l md:border-t-0 md:pl-10 md:pt-0"><p className="eyebrow text-[#718079]">Potential annual saving</p><p className="mt-2 text-5xl font-semibold text-[#b9f35a]">£{Math.round(roi.save).toLocaleString("en-GB")}</p><div className="mt-7 grid grid-cols-2 gap-4 border-t border-white/10 pt-5"><div><p className="text-2xl">£{Math.round(roi.cost).toLocaleString("en-GB")}</p><p className="text-xs text-[#718079]">current annual cost</p></div><div><p className="text-2xl">{Math.round(roi.time)}h</p><p className="text-xs text-[#718079]">back each month</p></div></div></div></div></div></div></section>
      <section id="results" className="mx-auto max-w-7xl px-5 py-24 lg:px-8 lg:py-32"><p className="eyebrow">Proof over promises</p><h2 className="mt-5 text-4xl font-semibold tracking-[-.05em] lg:text-6xl">Better systems. <span className="text-[#718079]">Visible results.</span></h2><div className="mt-14 grid gap-5 lg:grid-cols-3">{proofs.map((x, i) => <article key={x.tag} className="flex min-h-[390px] flex-col justify-between rounded-2xl border border-white/10 bg-[#111918] p-7 hover:-translate-y-1 hover:border-[#b9f35a]/40"><div><div className="flex justify-between"><span className={`rounded-full px-3 py-1 text-[10px] tracking-[.16em] ${i === 0 ? "bg-[#b9f35a]/15 text-[#b9f35a]" : i === 1 ? "bg-violet-400/15 text-violet-300" : "bg-orange-400/15 text-orange-300"}`}>{x.tag}</span><span className="font-mono text-xs text-[#52615a]">0{i + 1}</span></div><h3 className="mt-12 text-2xl leading-tight">{x.title}</h3><p className="mt-4 text-sm leading-relaxed text-[#89958e]">{x.body}</p></div><div className="mt-10 border-t border-white/10 pt-5"><p className="text-4xl font-semibold text-[#b9f35a]">{x.m}</p><p className="text-xs text-[#718079]">{x.ml}</p></div></article>)}</div></section>
      <section id="process" className="border-y border-white/[.08] bg-[#b9f35a] px-5 py-24 text-[#11170d] lg:px-8 lg:py-32"><div className="mx-auto max-w-7xl"><p className="eyebrow text-[#3f582d]">How we work</p><h2 className="mt-5 max-w-md text-4xl font-semibold tracking-[-.05em] lg:text-6xl">Small steps. Serious momentum.</h2><div className="veltro-steps mt-12 grid gap-3 sm:grid-cols-2">{steps.map((x, i) => <div key={x.n} className={`veltro-step veltro-step-${i} p-7`}><span className="veltro-step-number font-mono text-xs">{x.n}</span><div className="veltro-step-line" /><h3 className="mt-12 text-xl font-semibold">{x.t}</h3><p className="mt-3 max-w-xs text-sm">{x.b}</p></div>)}</div></div></section>
      <section id="pricing" className="mx-auto max-w-7xl px-5 py-24 lg:px-8 lg:py-32"><div className="grid gap-12 lg:grid-cols-[.7fr_1.3fr]"><div><p className="eyebrow">Clear starting points</p><h2 className="mt-5 text-4xl font-semibold tracking-[-.05em] lg:text-5xl">Start where the value is.</h2><p className="mt-6 max-w-sm text-sm text-[#89958e]">Start small, build momentum, or change the operating model entirely.</p></div><div className="grid gap-4 md:grid-cols-3">{plans.map((x, i) => <div key={x.t} className={`veltro-plan veltro-plan-${i} group rounded-2xl border p-6 ${i === 1 ? "border-[#b9f35a]/50 bg-[#b9f35a]/10" : "border-white/10 bg-[#111918]"}`}><div className="flex items-start justify-between"><h3 className="text-lg font-medium">{x.t}</h3>{i === 1 && <span className="rounded-full bg-[#b9f35a] px-2 py-1 text-[9px] font-bold text-[#11170d]">POPULAR</span>}</div><p className="mt-8 text-3xl font-semibold tracking-tight">{x.p}</p><p className="mt-3 min-h-[72px] text-sm leading-relaxed text-[#89958e]">{x.s}</p><div className="mt-7 space-y-3 border-t border-white/10 pt-5">{x.b.map(b => <p key={b} className="flex gap-2 text-xs text-[#b8c3bc]"><Check className="h-4 w-4 shrink-0 text-[#b9f35a]" />{b}</p>)}</div><div className="veltro-plan-orbit" /></div>)}</div></div></section>
      <section id="contact" className="border-t border-white/[.08] bg-[#101716] px-5 py-24 lg:px-8 lg:py-32"><div className="mx-auto grid max-w-7xl gap-14 lg:grid-cols-[1fr_.8fr] lg:items-center"><div><p className="eyebrow">Your next useful conversation</p><h2 className="mt-5 max-w-2xl text-5xl font-semibold leading-[.95] tracking-[-.06em] lg:text-7xl">Tell us what is <span className="text-[#b9f35a]">slowing you down.</span></h2><p className="mt-7 max-w-lg text-[#89958e]">Share a few details and we will come back with a useful first conversation — no hard sell, no vague proposal.</p></div><div className="rounded-2xl border border-white/10 bg-[#0b1010] p-6 md:p-8">{sent ? <div className="py-10 text-center"><CheckCircle2 className="mx-auto h-12 w-12 text-[#b9f35a]" /><h3 className="mt-5 text-2xl">You are on the list.</h3><p className="mt-3 text-sm text-[#89958e]">We will be in touch soon.</p></div> : <form onSubmit={submit} className="space-y-4"><Input required type="email" value={email} onChange={e => setEmail(e.target.value)} placeholder="Work email" className="h-12 rounded-xl border-white/10 bg-white/5 text-white" /><div className="grid gap-4 sm:grid-cols-2"><Input value={name} onChange={e => setName(e.target.value)} placeholder="Your name" className="h-12 rounded-xl border-white/10 bg-white/5 text-white" /><Input value={company} onChange={e => setCompany(e.target.value)} placeholder="Company" className="h-12 rounded-xl border-white/10 bg-white/5 text-white" /></div><Button disabled={sending} type="submit" className="w-full rounded-full bg-[#b9f35a] py-4 font-semibold text-[#11170d] hover:bg-[#d4ff8b]">{sending ? "Sending…" : "Start the conversation"}<ArrowRight className="ml-2 h-4 w-4" /></Button><p className="text-center text-xs text-[#52615a]">No spam. No obligation. Just a useful first chat.</p></form>}</div></div></section>
    </main><footer className="border-t border-white/[.08] px-5 py-8"><div className="mx-auto flex max-w-7xl justify-between text-xs text-[#718079]"><span>© {new Date().getFullYear()} Veltro · Forward development engineering</span><div className="flex gap-5"><a href="/privacy">Privacy</a><a href="/terms">Terms</a></div></div></footer>
  </div>;
}
