import {
  LEDGER_CURRENT,
  THREE_CDN,
  type MotionCategory,
  type MotionSchema,
} from "./motionSchema";
import { DEFAULT_DRIP_WIDGET } from "./motionWidget";

export type MotionPresetGroup = "Atmosphere" | "Graphic devices" | "Structure" | "Occasional";

export type MotionPreset = {
  id: string;
  name: string;
  group: MotionPresetGroup;
  schema: MotionSchema;
};

export const MOTION_PRESET_GROUPS: MotionPresetGroup[] = [
  "Atmosphere",
  "Graphic devices",
  "Structure",
  "Occasional",
];

const INK_BLUE_PAPER = ["#1A1D21", "#2F5199", "#F7F5F1"] as const;

const VIBE_KEYWORDS: Record<string, string[]> = {
  "ledger-current": ["liquid", "wind", "current", "silk", "smoke"],
  "paper-sparks": ["moody", "starry", "dust", "sparks"],
  "grain-breath": ["grain", "film", "tooth"],
  "after-hours-warp": ["distortion", "glass", "heat", "warp"],
  "stamp-pulse": ["stamp", "slam", "seal"],
  "redact-sweep": ["redact", "bar", "myth"],
  "ink-bleed": ["letterpress", "bleed"],
  "light-leak": ["leak", "flare"],
  "corporate-ribbon": ["clean", "wave", "ribbon", "flag"],
  "perspective-grid": ["grid", "retro", "city"],
  "network-map": ["network", "introducer"],
  "hook-turn": ["hook", "kinetic", "word"],
  "ledger-ticker": ["ticker", "numerals", "ledger"],
  "goo-merge": ["goo", "blob", "merge"],
  "shatter-plate": ["shatter", "crack"],
  "vapor-drift": ["vapor", "mist", "fog", "drift"],
  "static-shiver": ["static", "shiver", "crt", "noise"],
  "vignette-breathing": ["vignette", "breathing", "edge"],
  "horizon-shift": ["horizon", "lean", "shift"],
  "carbon-weave": ["carbon", "weave", "parallax", "depth"],
  "parchment-heat": ["parchment", "heat", "haze"],
  "ledger-fracture": ["fracture", "crack", "glass"],
  "cybernetic-scanline": ["scanline", "scan", "cyber"],
  "ledger-margin-glow": ["margin", "glow"],
  "resin-gloss-sweep": ["resin", "gloss", "sweep"],
  "holographic-foil": ["holographic", "foil", "iridescence", "sheen"],
  "vellum-crease": ["vellum", "crease", "fold"],
  "elastic-spring": ["elastic", "spring", "reveal"],
  "kinetic-squeeze": ["kinetic", "squeeze", "stretch"],
  "crosshair-grid-track": ["crosshair", "track", "cursor"],
  "typewriter-cursor": ["typewriter", "cursor", "blink"],
  "ledger-stitch": ["stitch", "seam", "dash"],
  "ink-splash-bloom": ["splash", "bloom"],
  "quantum-glitch": ["glitch", "quantum", "burst"],
  "ink-ripple": ["ripple", "distortion"],
  "focus-pull": ["focus", "pull", "blur", "rack"],
  "magnetic-ripple": ["magnetic", "ripple", "pop", "ring"],
  "kinetic-strobe-pulse": ["strobe", "flicker"],
  "kinetic-momentum-glide": ["momentum", "glide", "inertia"],
  "prismatic-focal-shift": ["prismatic", "fringe"],
  "liquid-quartz": ["quartz", "fluidity", "tension"],
  "anode-flicker-decay": ["anode", "decay", "dim", "cathode"],
  "acoustic-waveform-pulse": ["acoustic", "waveform", "transcription"],
  "magnetic-edge-snap": ["snap", "dock", "recoil"],
  "thermal-heat-bloom": ["thermal", "bloom", "warmth"],
  "dynamic-focal-vignette": ["writing", "density", "focal"],
  "kinetic-stencil-punch": ["stencil", "punch", "cutout"],
  "vellum-hysteresis": ["hysteresis", "lag", "memory"],
  "phosphor-burn-in": ["phosphor", "ghost", "burn"],
  "quantum-entanglement": ["entanglement", "linked"],
  "resonance-blur": ["resonance", "clatter", "typing"],
  "gravitational-field": ["gravitational", "gravity", "tooltip"],
  "guilloche-wave": ["guilloche", "security", "rosette"],
  "topographic-contour": ["topographic", "contour"],
  "origami-unfold": ["origami", "unfold"],
  "elastic-threading": ["threading", "bezier"],
  "isometric-extrusion": ["isometric", "blueprint", "extrusion"],
  "mechanical-escapement": ["escapement", "gear", "interlock"],
  "voronoi-partition": ["partition", "cell"],
  "viral-hook-drop": ["viral", "overshoot", "thumb"],
  "liquid-glass-shift": ["chrome", "shift", "liquid", "glass"],
  "cinematic-hook-slam": ["cinematic", "slam"],
  "liquid-text-mask": ["matte", "mask"],
  "glowing-pill-pulse": ["pill", "badge", "capsule"],
  "odometer-roll": ["odometer", "digits", "counter"],
  "redact-highlight": ["highlight", "wipe"],
  "dripping-text": ["drip", "dripping", "melt", "teardrop", "honey", "slime", "pour", "droplet"],
  "kinetic-word-press": ["piston", "press", "engine", "word"],
  "kinetic-assembly": ["assembly", "assemble", "machine", "spells"],
  "breathing-monument": ["monument", "breathing", "breathe", "slow"],
  "stroke-reveal-check": ["stroke", "reveal", "check", "loading", "approve"],
  "telemetry-ghost": ["telemetry", "ghost", "scan", "lock", "surveillance"],
  "vanishing-point-tunnel": ["tunnel", "vanishing", "portal", "polygon"],
  "word-vortex": ["vortex", "tornado", "spin", "word"],
  "chromatic-misregister": ["misregister", "cathedral", "error", "glitch", "rgb"],
  "icon-weather-system": ["weather", "icons", "rain", "storm", "symbols"],
  "reality-buffering": ["buffering", "loading", "glitch", "retry"],
  "stillness-static": ["static", "stillness", "resolve", "noise"],
  "declassified-text": ["declassified", "redact", "redacted", "bars", "classified"],
  "kintsugi-mend": ["kintsugi", "crack", "gold", "mend", "repair"],
  "ferrofluid-pull": ["ferrofluid", "magnet", "spike", "fluid"],
  "slow-fax": ["fax", "print", "thermal", "receiving"],
  "sundial-shadow": ["sundial", "shadow", "time", "clock", "daylight"],
  "halftone-lamp": ["halftone", "lamp", "dots", "light"],
  "hourglass-countdown": ["hourglass", "countdown", "sand", "timer", "deadline"],
  murmuration: ["murmuration", "flock", "birds", "boids", "swarm"],
  "pendulum-letters": ["pendulum", "swing", "thread", "letters"],
  "favicon-escape": ["favicon", "tab", "escape", "browser"],
  "absence-bloom": ["absence", "moss", "bloom", "away", "grow"],
  "selection-ink": ["selection", "ink", "highlight", "collect", "pile"],
};

function house(
  id: string,
  name: string,
  group: MotionPresetGroup,
  category: MotionCategory,
  vibe: string,
  opts: {
    blending?: MotionSchema["visual"]["blending"];
    opacity?: number;
    grain?: number;
    background?: string;
    palette?: readonly string[];
    density?: number;
    speed?: number;
    amplitude?: number;
    frequency?: number;
    friction?: number;
    trigger?: MotionSchema["interactionRules"]["triggerType"];
    radius?: number;
    strength?: number;
    falloff?: "smooth" | "linear";
  } = {},
): MotionPreset {
  return {
    id,
    name,
    group,
    schema: {
      ...LEDGER_CURRENT,
      meta: { title: name.charAt(0) + name.slice(1).toLowerCase(), vibe },
      category,
      visual: {
        ...LEDGER_CURRENT.visual,
        blending: opts.blending ?? LEDGER_CURRENT.visual.blending,
        opacity: opts.opacity ?? 0.88,
        grain: opts.grain ?? 0.04,
        background: opts.background ?? LEDGER_CURRENT.visual.background,
        palette: [...(opts.palette ?? INK_BLUE_PAPER)],
      },
      physicsAndMath: {
        ...LEDGER_CURRENT.physicsAndMath,
        densityCount: opts.density ?? 48,
        speed: opts.speed ?? 0.45,
        amplitude: opts.amplitude ?? 16,
        frequency: opts.frequency ?? 1.2,
        friction: opts.friction ?? LEDGER_CURRENT.physicsAndMath.friction,
      },
      interactionRules: {
        triggerType: opts.trigger ?? "none",
        influenceRadius: opts.radius ?? 0,
        strength: opts.strength ?? 0,
        falloff: opts.falloff ?? "smooth",
      },
    },
  };
}

export const MOTION_PRESETS: MotionPreset[] = [
  {
    id: "ledger-current",
    name: "Ledger Current",
    group: "Atmosphere",
    schema: LEDGER_CURRENT,
  },
  {
    id: "paper-sparks",
    name: "Paper Sparks",
    group: "Atmosphere",
    schema: {
      ...LEDGER_CURRENT,
      meta: { title: "Paper sparks", vibe: "moody starry dust motes and sparks over a ledger, screen blend" },
      category: "ParticleSystem",
      visual: {
        ...LEDGER_CURRENT.visual,
        blending: "source-over",
        opacity: 0.9,
        grain: 0.04,
        palette: [...INK_BLUE_PAPER],
      },
      physicsAndMath: { ...LEDGER_CURRENT.physicsAndMath, densityCount: 220, speed: 0.35, friction: 0.08 },
      interactionRules: { ...LEDGER_CURRENT.interactionRules, triggerType: "none" },
    },
  },
  {
    id: "grain-breath",
    name: "Grain Breath",
    group: "Atmosphere",
    schema: {
      ...LEDGER_CURRENT,
      meta: { title: "Grain breath", vibe: "paper tooth and film grain that barely moves" },
      category: "GrainField",
      visual: {
        ...LEDGER_CURRENT.visual,
        opacity: 0.28,
        grain: 0.12,
        blending: "multiply",
        palette: [...INK_BLUE_PAPER],
      },
      physicsAndMath: { ...LEDGER_CURRENT.physicsAndMath, densityCount: 80, speed: 0.08, amplitude: 6 },
      interactionRules: { triggerType: "none", influenceRadius: 0, strength: 0, falloff: "smooth" },
    },
  },
  {
    id: "after-hours-warp",
    name: "After-hours Warp",
    group: "Atmosphere",
    schema: {
      ...LEDGER_CURRENT,
      meta: { title: "After-hours warp", vibe: "glass heat distortion warp after closing" },
      category: "CustomShaderDistortion",
      engine: { library: "ThreeJS", renderContext: "webgl", cdn: THREE_CDN },
      visual: {
        ...LEDGER_CURRENT.visual,
        opacity: 0.8,
        grain: 0.05,
        blending: "source-over",
        palette: [...INK_BLUE_PAPER],
      },
      physicsAndMath: { ...LEDGER_CURRENT.physicsAndMath, densityCount: 64, speed: 0.4, amplitude: 18, frequency: 1.1 },
      interactionRules: { ...LEDGER_CURRENT.interactionRules, triggerType: "mousemove", influenceRadius: 200, strength: 0.9 },
    },
  },
  house("vapor-drift", "Vapor Drift", "Atmosphere", "VaporDrift", "slow mist vapor drift across paper", {
    opacity: 0.55,
    grain: 0.06,
    density: 36,
    speed: 0.18,
    amplitude: 22,
  }),
  house("static-shiver", "Static Shiver", "Atmosphere", "StaticShiver", "crt static shiver noise on the plate", {
    opacity: 0.42,
    grain: 0.1,
    density: 90,
    speed: 1.2,
    amplitude: 1.5,
    frequency: 4,
  }),
  house("vignette-breathing", "Vignette Breathing", "Atmosphere", "VignetteBreath", "vignette breathing dark edge pulse", {
    opacity: 0.7,
    grain: 0.03,
    speed: 0.32,
    amplitude: 10,
  }),
  house("horizon-shift", "Horizon Shift", "Atmosphere", "HorizonShift", "subtle horizon lean shift between panes", {
    opacity: 0.86,
    grain: 0.03,
    speed: 0.2,
    amplitude: 8,
    frequency: 0.5,
  }),
  house("carbon-weave", "Carbon Weave", "Atmosphere", "CarbonWeave", "carbon weave parallax depth from the cursor", {
    opacity: 0.8,
    grain: 0.05,
    density: 28,
    speed: 0.25,
    trigger: "mousemove",
    radius: 240,
    strength: 0.8,
  }),
  house("parchment-heat", "Parchment Heat", "Atmosphere", "HeatHaze", "parchment heat haze ripple across the header", {
    opacity: 0.78,
    grain: 0.05,
    speed: 0.55,
    amplitude: 5,
    frequency: 4,
  }),
  house("liquid-quartz", "Liquid Quartz", "Atmosphere", "QuartzFluid", "liquid quartz surface tension on hover", {
    opacity: 0.8,
    grain: 0.04,
    speed: 0.64,
    amplitude: 10,
    frequency: 4,
    trigger: "hover",
    radius: 160,
    strength: 0.9,
  }),
  house("liquid-glass-shift", "Liquid Glass Shift", "Atmosphere", "LiquidGlass", "liquid glass chrome shift across the plate", {
    blending: "source-over",
    background: "#1A1D21",
    opacity: 0.94,
    grain: 0.05,
    speed: 0.55,
    amplitude: 20,
    frequency: 3,
    palette: ["#1A1D21", "#F7F5F1", "#2F5199"],
  }),
  house("thermal-heat-bloom", "Thermal Heat Bloom", "Atmosphere", "HeatBloom", "thermal warmth bloom during a long drafting session", {
    opacity: 0.62,
    grain: 0.04,
    speed: 0.08,
    amplitude: 5,
  }),
  house("dynamic-focal-vignette", "Dynamic Focal Vignette", "Atmosphere", "FocalVignette", "writing focus vignette that tightens density", {
    opacity: 0.78,
    grain: 0.03,
    speed: 0.4,
    amplitude: 75,
  }),
  house("vellum-hysteresis", "Vellum Hysteresis", "Atmosphere", "VellumHysteresis", "sub-pixel vellum hysteresis lag with physical memory", {
    opacity: 0.82,
    grain: 0.07,
    density: 24,
    speed: 0.22,
    amplitude: 12,
    trigger: "mousemove",
    radius: 220,
    strength: 0.7,
  }),
  house("gravitational-field", "Gravitational Field", "Atmosphere", "GravityWarp", "gravitational warp pulling nearby marks toward the cursor", {
    opacity: 0.86,
    grain: 0.04,
    density: 18,
    speed: 0.3,
    amplitude: 25,
    trigger: "mousemove",
    radius: 150,
    strength: 1.1,
  }),
  {
    id: "stamp-pulse",
    name: "Stamp Pulse",
    group: "Graphic devices",
    schema: {
      ...LEDGER_CURRENT,
      meta: { title: "Stamp pulse", vibe: "stamp slam seal ring with a gold needle" },
      category: "StampPulse",
      visual: {
        ...LEDGER_CURRENT.visual,
        opacity: 0.92,
        grain: 0.04,
        blending: "source-over",
        palette: ["#1A1D21", "#C69123", "#F7F5F1"],
      },
      physicsAndMath: { ...LEDGER_CURRENT.physicsAndMath, densityCount: 24, speed: 0.55, amplitude: 12, frequency: 1 },
      interactionRules: { triggerType: "click", influenceRadius: 80, strength: 1.4, falloff: "smooth" },
    },
  },
  {
    id: "redact-sweep",
    name: "Redact Sweep",
    group: "Graphic devices",
    schema: {
      ...LEDGER_CURRENT,
      meta: { title: "Redact sweep", vibe: "redact bar myth strike, never writes copy" },
      category: "RedactSweep",
      visual: {
        ...LEDGER_CURRENT.visual,
        opacity: 0.95,
        grain: 0.02,
        blending: "source-over",
        palette: ["#1A1D21", "#C91B25", "#F7F5F1"],
      },
      physicsAndMath: { ...LEDGER_CURRENT.physicsAndMath, densityCount: 16, speed: 0.6, amplitude: 8, frequency: 0.8 },
      interactionRules: { triggerType: "none", influenceRadius: 0, strength: 0, falloff: "smooth" },
    },
  },
  {
    id: "ink-bleed",
    name: "Ink Bleed",
    group: "Graphic devices",
    schema: {
      ...LEDGER_CURRENT,
      meta: { title: "Ink bleed", vibe: "letterpress bleed and misregistration squash" },
      category: "InkBleed",
      visual: {
        ...LEDGER_CURRENT.visual,
        opacity: 0.78,
        grain: 0.08,
        blending: "multiply",
        palette: [...INK_BLUE_PAPER],
      },
      physicsAndMath: { ...LEDGER_CURRENT.physicsAndMath, densityCount: 120, speed: 0.22, amplitude: 14, friction: 0.2 },
      interactionRules: { triggerType: "none", influenceRadius: 0, strength: 0, falloff: "smooth" },
    },
  },
  {
    id: "light-leak",
    name: "Light Leak",
    group: "Graphic devices",
    schema: {
      ...LEDGER_CURRENT,
      meta: { title: "Light leak", vibe: "one optical flare leak across paper" },
      category: "LightLeak",
      visual: {
        ...LEDGER_CURRENT.visual,
        opacity: 0.7,
        grain: 0.05,
        blending: "screen",
        palette: ["#F7F5F1", "#C69123", "#2F5199"],
      },
      physicsAndMath: { ...LEDGER_CURRENT.physicsAndMath, densityCount: 48, speed: 0.5, amplitude: 40, frequency: 0.6 },
      interactionRules: { triggerType: "none", influenceRadius: 0, strength: 0, falloff: "smooth" },
    },
  },
  house("ledger-fracture", "Ledger Fracture", "Graphic devices", "LedgerFracture", "ledger glass fracture crack on the plate", {
    opacity: 0.9,
    grain: 0.04,
    density: 18,
    speed: 0.5,
    amplitude: 30,
    trigger: "click",
    radius: 180,
    strength: 1.2,
    falloff: "linear",
  }),
  house("cybernetic-scanline", "Cybernetic Scanline", "Graphic devices", "ScanlineSweep", "cybernetic scanline sweep across the plate", {
    blending: "screen",
    opacity: 0.75,
    grain: 0.02,
    speed: 0.35,
    amplitude: 4,
  }),
  house("ledger-margin-glow", "Ledger Margin Glow", "Graphic devices", "MarginGlow", "soft margin glow pulse on the active edge", {
    opacity: 0.82,
    grain: 0.03,
    speed: 0.48,
    amplitude: 25,
  }),
  house("resin-gloss-sweep", "Resin Gloss Sweep", "Graphic devices", "ResinGloss", "high-gloss resin reflection sweep across glass", {
    blending: "source-over",
    opacity: 0.8,
    grain: 0.02,
    speed: 0.7,
    amplitude: 40,
    palette: ["#1A1D21", "#F7F5F1", "#2F5199"],
  }),
  house("holographic-foil", "Holographic Foil", "Graphic devices", "HoloFoil", "holographic foil sheen iridescence on hover", {
    opacity: 0.9,
    grain: 0.03,
    speed: 0.6,
    trigger: "hover",
    radius: 120,
    strength: 1,
  }),
  house("vellum-crease", "Vellum Crease", "Graphic devices", "VellumCrease", "vellum crease fold catching desk light", {
    opacity: 0.7,
    grain: 0.05,
    speed: 0.24,
    amplitude: 15,
  }),
  house("prismatic-focal-shift", "Prismatic Focal Shift", "Graphic devices", "PrismaticFringe", "prismatic rgb fringe burst on focus change", {
    blending: "screen",
    opacity: 0.88,
    grain: 0.03,
    speed: 0.7,
    amplitude: 4,
    frequency: 4,
    trigger: "click",
    radius: 140,
    strength: 1.1,
  }),
  house("magnetic-edge-snap", "Magnetic Edge Snap", "Graphic devices", "EdgeSnap", "elastic snap recoil when a card docks the grid", {
    opacity: 0.9,
    grain: 0.03,
    speed: 0.7,
    amplitude: 10,
    trigger: "click",
    radius: 80,
    strength: 1.2,
  }),
  house("kinetic-stencil-punch", "Kinetic Stencil Punch", "Graphic devices", "StencilPunch", "stencil punch cutout letters with a depth shadow", {
    opacity: 0.94,
    grain: 0.03,
    speed: 0.55,
    amplitude: 25,
  }),
  house("guilloche-wave", "Guilloche Wave", "Graphic devices", "GuillocheWave", "guilloche security wave on overlapping line art", {
    opacity: 0.88,
    grain: 0.03,
    density: 3,
    speed: 0.4,
    amplitude: 15,
    frequency: 4,
  }),
  house("origami-unfold", "Origami Unfold", "Graphic devices", "OrigamiUnfold", "origami document unfold from a folded panel", {
    opacity: 0.9,
    grain: 0.03,
    speed: 0.45,
    amplitude: 90,
  }),
  house("isometric-extrusion", "Isometric Extrusion", "Graphic devices", "IsoExtrude", "isometric blueprint extrusion from wireframe", {
    opacity: 0.9,
    grain: 0.03,
    speed: 0.5,
    amplitude: 45,
  }),
  house("mechanical-escapement", "Mechanical Escapement", "Graphic devices", "Escapement", "mechanical escapement gear interlock during a save", {
    opacity: 0.9,
    grain: 0.03,
    density: 12,
    speed: 0.5,
  }),
  house("glowing-pill-pulse", "Glowing Pill Pulse", "Graphic devices", "PillPulse", "glowing pill badge pulse on a lead-gen capsule", {
    opacity: 0.9,
    grain: 0.02,
    speed: 0.48,
    amplitude: 25,
  }),
  house("redact-highlight", "Redact Highlight", "Graphic devices", "RedactHighlight", "redacted highlight box wipe across the hook", {
    opacity: 0.92,
    grain: 0.02,
    speed: 0.7,
    amplitude: 8,
  }),
  {
    id: "corporate-ribbon",
    name: "Corporate Ribbon",
    group: "Structure",
    schema: {
      ...LEDGER_CURRENT,
      meta: { title: "Corporate ribbon", vibe: "clean strata wave ribbon flag, blue on paper" },
      category: "SineWaveRibbon",
      visual: {
        ...LEDGER_CURRENT.visual,
        opacity: 0.9,
        grain: 0.03,
        palette: ["#2F5199", "#1A1D21", "#F7F5F1"],
      },
      physicsAndMath: { ...LEDGER_CURRENT.physicsAndMath, densityCount: 8, speed: 0.45, amplitude: 28, frequency: 1.6 },
      interactionRules: { triggerType: "none", influenceRadius: 0, strength: 0, falloff: "smooth" },
    },
  },
  {
    id: "perspective-grid",
    name: "Perspective Grid",
    group: "Structure",
    schema: {
      ...LEDGER_CURRENT,
      meta: { title: "Perspective grid", vibe: "retro city grid vanishing into paper" },
      category: "PerspectiveGrid",
      visual: {
        ...LEDGER_CURRENT.visual,
        opacity: 0.88,
        grain: 0.03,
        palette: [...INK_BLUE_PAPER],
      },
      physicsAndMath: { ...LEDGER_CURRENT.physicsAndMath, densityCount: 32, speed: 0.3, amplitude: 20, frequency: 1.4 },
      interactionRules: { triggerType: "scroll", influenceRadius: 120, strength: 0.8, falloff: "linear" },
    },
  },
  {
    id: "network-map",
    name: "Network Map",
    group: "Structure",
    schema: {
      ...LEDGER_CURRENT,
      meta: { title: "Network map", vibe: "introducer network nodes and thin edges" },
      category: "NetworkGraph",
      visual: {
        ...LEDGER_CURRENT.visual,
        opacity: 0.86,
        grain: 0.04,
        palette: [...INK_BLUE_PAPER],
      },
      physicsAndMath: { ...LEDGER_CURRENT.physicsAndMath, densityCount: 36, speed: 0.25, amplitude: 10, friction: 0.18 },
      interactionRules: { triggerType: "hover", influenceRadius: 100, strength: 1, falloff: "smooth" },
    },
  },
  {
    id: "hook-turn",
    name: "Hook Turn",
    group: "Structure",
    schema: {
      ...LEDGER_CURRENT,
      meta: { title: "Hook turn", vibe: "kinetic word hook turn reading sibling hooks" },
      category: "TypeKinetic",
      visual: {
        ...LEDGER_CURRENT.visual,
        opacity: 0.95,
        grain: 0.02,
        palette: [...INK_BLUE_PAPER],
      },
      physicsAndMath: { ...LEDGER_CURRENT.physicsAndMath, densityCount: 12, speed: 0.4, amplitude: 16, frequency: 1 },
      interactionRules: { triggerType: "none", influenceRadius: 0, strength: 0, falloff: "smooth" },
    },
  },
  {
    id: "ledger-ticker",
    name: "Ledger Ticker",
    group: "Structure",
    schema: {
      ...LEDGER_CURRENT,
      meta: { title: "Ledger ticker", vibe: "mono numerals ticker: LEDGER, ON TIME, FILE 04, ISO dates" },
      category: "DataTicker",
      visual: {
        ...LEDGER_CURRENT.visual,
        opacity: 0.9,
        grain: 0.02,
        palette: [...INK_BLUE_PAPER],
      },
      physicsAndMath: { ...LEDGER_CURRENT.physicsAndMath, densityCount: 20, speed: 0.65, amplitude: 4, frequency: 1.2 },
      interactionRules: { triggerType: "none", influenceRadius: 0, strength: 0, falloff: "smooth" },
    },
  },
  house("elastic-spring", "Elastic Spring", "Structure", "ElasticSpring", "elastic spring reveal on a card plate", {
    opacity: 0.92,
    grain: 0.02,
    speed: 0.5,
    amplitude: 50,
    frequency: 1.5,
  }),
  house("kinetic-squeeze", "Kinetic Squeeze", "Structure", "KineticSqueeze", "kinetic squeeze stretch on moving type", {
    opacity: 0.94,
    grain: 0.02,
    speed: 0.55,
    amplitude: 18,
  }),
  house("crosshair-grid-track", "Crosshair Grid Track", "Structure", "CrosshairGrid", "crosshair grid that tracks the cursor with lag", {
    opacity: 0.84,
    grain: 0.03,
    density: 16,
    speed: 0.4,
    trigger: "mousemove",
    radius: 200,
    strength: 0.7,
  }),
  house("typewriter-cursor", "Typewriter Cursor", "Structure", "TypewriterCursor", "typewriter cursor blink on the active file", {
    opacity: 0.95,
    grain: 0.02,
    speed: 0.5,
  }),
  house("ledger-stitch", "Ledger Stitch", "Structure", "LedgerStitch", "ledger stitch seam draws around the card", {
    opacity: 0.9,
    grain: 0.03,
    speed: 0.55,
    amplitude: 8,
  }),
  house("kinetic-momentum-glide", "Kinetic Momentum Glide", "Structure", "MomentumGlide", "weighted momentum glide on a heavy glass panel", {
    opacity: 0.9,
    grain: 0.03,
    speed: 0.35,
    amplitude: 50,
  }),
  house("acoustic-waveform-pulse", "Acoustic Waveform Pulse", "Structure", "WaveformPulse", "acoustic waveform pulse while transcription is listening", {
    opacity: 0.9,
    grain: 0.02,
    density: 32,
    speed: 1.2,
    amplitude: 15,
    frequency: 12,
  }),
  house("resonance-blur", "Resonance Blur", "Structure", "ResonanceBlur", "aero-mechanical resonance blur from high typing velocity", {
    opacity: 0.9,
    grain: 0.02,
    speed: 0.85,
    amplitude: 45,
  }),
  house("topographic-contour", "Topographic Contour", "Structure", "TopoContour", "topographic word-density contours that breathe with copy length", {
    opacity: 0.86,
    grain: 0.03,
    density: 6,
    speed: 0.32,
    amplitude: 3,
  }),
  house("elastic-threading", "Elastic Threading", "Structure", "ElasticThread", "elastic bezier threading with spring tension", {
    opacity: 0.9,
    grain: 0.02,
    speed: 0.55,
    amplitude: 40,
    frequency: 3,
  }),
  house("voronoi-partition", "Voronoi Partition", "Structure", "VoronoiPulse", "voronoi cell partition pulse across the grid", {
    opacity: 0.88,
    grain: 0.03,
    density: 14,
    speed: 0.6,
    amplitude: 8,
  }),
  house("liquid-text-mask", "Liquid Text Mask", "Structure", "TextMaskShift", "liquid gradient text mask shifting through the hook", {
    opacity: 0.94,
    grain: 0.02,
    speed: 0.6,
    amplitude: 25,
  }),
  house("odometer-roll", "Odometer Roll", "Structure", "OdometerRoll", "mechanical odometer digits rolling a live counter", {
    opacity: 0.92,
    grain: 0.02,
    speed: 0.55,
    amplitude: 20,
  }),
  {
    id: "dripping-text",
    name: "Dripping Text",
    group: "Structure",
    schema: {
      ...LEDGER_CURRENT,
      meta: {
        title: "Dripping text",
        vibe: "liquid droplets pour and merge into a word, drip melt teardrop",
      },
      category: "DrippingText",
      visual: {
        ...LEDGER_CURRENT.visual,
        palette: ["#C8F04A", "#F4F0E8", "#93B52F", "#6F8A22"],
        background: "#11130F",
        blending: "source-over",
        opacity: 0.96,
        grain: 0.04,
      },
      physicsAndMath: {
        ...LEDGER_CURRENT.physicsAndMath,
        densityCount: 1200,
        speed: 1.15,
        amplitude: 48,
        friction: 0.16,
      },
      interactionRules: { triggerType: "click", influenceRadius: 120, strength: 1.2, falloff: "smooth" },
      widget: { ...DEFAULT_DRIP_WIDGET },
    },
  },
  {
    id: "goo-merge",
    name: "Goo Merge",
    group: "Occasional",
    schema: {
      ...LEDGER_CURRENT,
      meta: { title: "Goo merge", vibe: "lawful goo blob merge on paper" },
      category: "MetaballGoo",
      visual: {
        ...LEDGER_CURRENT.visual,
        opacity: 0.82,
        grain: 0.05,
        blending: "source-over",
        palette: [...INK_BLUE_PAPER],
      },
      physicsAndMath: { ...LEDGER_CURRENT.physicsAndMath, densityCount: 28, speed: 0.35, amplitude: 24, friction: 0.12 },
      interactionRules: { triggerType: "mousemove", influenceRadius: 140, strength: 1.1, falloff: "smooth" },
    },
  },
  {
    id: "shatter-plate",
    name: "Shatter Plate",
    group: "Occasional",
    schema: {
      ...LEDGER_CURRENT,
      meta: { title: "Shatter plate", vibe: "shatter crack plate on click" },
      category: "VoronoiShatter",
      visual: {
        ...LEDGER_CURRENT.visual,
        opacity: 0.9,
        grain: 0.04,
        palette: [...INK_BLUE_PAPER],
      },
      physicsAndMath: { ...LEDGER_CURRENT.physicsAndMath, densityCount: 40, speed: 0.7, amplitude: 30, frequency: 1.5 },
      interactionRules: { triggerType: "click", influenceRadius: 200, strength: 1.6, falloff: "linear" },
    },
  },
  house("ink-splash-bloom", "Ink Splash Bloom", "Occasional", "InkSplash", "ink splash bloom from a click", {
    opacity: 0.88,
    grain: 0.04,
    density: 40,
    speed: 0.7,
    amplitude: 28,
    trigger: "click",
    radius: 160,
    strength: 1.3,
  }),
  house("quantum-glitch", "Quantum Glitch", "Occasional", "GlitchBurst", "quantum glitch burst rgb split", {
    blending: "screen",
    opacity: 0.86,
    grain: 0.05,
    speed: 0.8,
    amplitude: 8,
    frequency: 4,
  }),
  house("ink-ripple", "Ink Ripple", "Occasional", "InkRipple", "ink ripple distortion wave from a click", {
    opacity: 0.85,
    grain: 0.04,
    speed: 0.6,
    amplitude: 30,
    trigger: "click",
    radius: 180,
    strength: 1.2,
  }),
  house("focus-pull", "Focus Pull", "Occasional", "FocusPull", "cinematic rack focus pull blur into the plate", {
    opacity: 0.9,
    grain: 0.03,
    speed: 0.4,
    amplitude: 25,
  }),
  house("magnetic-ripple", "Magnetic Ripple", "Occasional", "MagneticRipple", "magnetic ripple pop ring when a block locks", {
    opacity: 0.9,
    grain: 0.03,
    speed: 0.65,
    amplitude: 40,
    trigger: "click",
    radius: 160,
    strength: 1.4,
  }),
  house("kinetic-strobe-pulse", "Kinetic Strobe Pulse", "Occasional", "StrobePulse", "ultra-subtle strobe flicker during heavy inference", {
    opacity: 0.55,
    grain: 0.08,
    density: 70,
    speed: 1.4,
    amplitude: 8,
  }),
  house("anode-flicker-decay", "Anode Flicker Decay", "Occasional", "AnodeDecay", "anode cathode decay dim when the workspace closes", {
    opacity: 0.92,
    grain: 0.06,
    speed: 0.5,
    amplitude: 20,
  }),
  house("phosphor-burn-in", "Phosphor Burn-In", "Occasional", "PhosphorBurn", "phosphor ghost burn-in trailing high-contrast type", {
    blending: "screen",
    opacity: 0.8,
    grain: 0.05,
    speed: 0.55,
    amplitude: 40,
  }),
  house("quantum-entanglement", "Quantum Entanglement", "Occasional", "EntanglePulse", "entanglement pulse warping linked nodes in sync", {
    opacity: 0.86,
    grain: 0.04,
    density: 12,
    speed: 0.7,
    amplitude: 15,
    frequency: 8,
  }),
  house("viral-hook-drop", "Viral Hook Drop", "Occasional", "ViralHook", "viral hook drop overshoot for thumb-stopping reels", {
    opacity: 0.95,
    grain: 0.02,
    speed: 0.7,
    amplitude: 28,
    frequency: 4.5,
    background: "transparent",
  }),
  house("cinematic-hook-slam", "Cinematic Hook Slam", "Occasional", "HookSlam", "cinematic strobe-scale hook slam for scroll-stopping headers", {
    opacity: 0.96,
    grain: 0.02,
    speed: 0.7,
    amplitude: 45,
    frequency: 4.2,
    background: "transparent",
  }),
  house("kinetic-word-press", "Kinetic Word Press", "Structure", "WordPiston", "letters firing like pistons on a mechanical word press", {
    opacity: 0.92,
    grain: 0.03,
    density: 24,
    speed: 0.9,
    amplitude: 16,
  }),
  house("kinetic-assembly", "Kinetic Assembly", "Structure", "LetterAssembly", "letters fly in, lock into the word, then break into geometric parts", {
    opacity: 0.92,
    grain: 0.03,
    density: 20,
    speed: 0.7,
    amplitude: 20,
  }),
  house("breathing-monument", "Breathing Monument", "Atmosphere", "MonumentBreathe", "huge type breathing slowly with a drifting gradient", {
    opacity: 0.86,
    grain: 0.03,
    speed: 0.5,
    amplitude: 12,
  }),
  house("stroke-reveal-check", "Stroke Reveal Check", "Graphic devices", "StrokeReveal", "a checkmark stroke draws itself in, loading bar underneath", {
    opacity: 0.94,
    grain: 0.02,
    speed: 0.7,
    amplitude: 10,
  }),
  house("telemetry-ghost", "Telemetry Ghost", "Graphic devices", "TelemetryOverlay", "instrument overlay scanning and flickering to keep a lock on the word", {
    opacity: 0.9,
    grain: 0.04,
    speed: 0.6,
    amplitude: 8,
  }),
  house("vanishing-point-tunnel", "Vanishing Point Tunnel", "Atmosphere", "VanishingTunnel", "stacked polygons flying from a vanishing point that follows the cursor", {
    opacity: 0.82,
    grain: 0.04,
    speed: 0.6,
    amplitude: 20,
    trigger: "mousemove",
    radius: 220,
    strength: 0.8,
  }),
  house("word-vortex", "Word Vortex", "Occasional", "WordVortex", "typographic vortex spinning copies of the word around a sharp core", {
    opacity: 0.92,
    grain: 0.03,
    speed: 0.8,
    amplitude: 20,
    trigger: "mousemove",
    radius: 200,
    strength: 0.6,
  }),
  house("chromatic-misregister", "Chromatic Misregister", "Occasional", "MisregisterGlitch", "misregistered duplicate layers in clashing colour, screen blend", {
    blending: "screen",
    opacity: 0.88,
    grain: 0.04,
    speed: 0.9,
    amplitude: 14,
  }),
  house("icon-weather-system", "Icon Weather System", "Occasional", "IconWeather", "symbols raining like weather around the word", {
    opacity: 0.9,
    grain: 0.02,
    density: 90,
    speed: 0.8,
    amplitude: 14,
    trigger: "mousemove",
    radius: 110,
    strength: 0.8,
  }),
  house("reality-buffering", "Reality Buffering", "Graphic devices", "BufferGlitch", "the word stays still while the chrome around it keeps failing to load", {
    opacity: 0.92,
    grain: 0.03,
    speed: 0.5,
    amplitude: 8,
  }),
  house("stillness-static", "Stillness Static", "Occasional", "StaticResolve", "the word resolves out of static then scrambles again", {
    opacity: 0.9,
    grain: 0.05,
    speed: 0.8,
    amplitude: 10,
  }),
  house("declassified-text", "Declassified Text", "Occasional", "RedactionLift", "a redacted paragraph declassifies itself word by word then reseals", {
    opacity: 0.92,
    grain: 0.02,
    speed: 0.6,
    amplitude: 8,
  }),
  house("kintsugi-mend", "Kintsugi Mend", "Structure", "KintsugiMend", "the word cracks into shards and the seams heal with gold", {
    opacity: 0.92,
    grain: 0.03,
    speed: 0.7,
    amplitude: 14,
  }),
  house("ferrofluid-pull", "Ferrofluid Pull", "Occasional", "FerrofluidPull", "dark magnetic fluid spiking toward a wandering pull point", {
    background: "#D9D3C4",
    palette: ["#0A0A0A", "#2F5199", "#F7F5F1"],
    opacity: 0.92,
    grain: 0.02,
    speed: 0.7,
    amplitude: 14,
    trigger: "mousemove",
    radius: 140,
    strength: 0.8,
  }),
  house("slow-fax", "Slow Fax", "Graphic devices", "SlowFax", "a thermal fax printing the word line by line", {
    background: "#2A2D23",
    opacity: 0.94,
    grain: 0.03,
    speed: 0.6,
    amplitude: 8,
  }),
  house("sundial-shadow", "Sundial Type", "Atmosphere", "SundialShadow", "shadows cast by the real local time of day, glowing at night", {
    background: "#D9D3C4",
    opacity: 0.86,
    grain: 0.03,
    speed: 0.4,
    amplitude: 10,
  }),
  house("halftone-lamp", "Halftone Lamp", "Graphic devices", "HalftoneLamp", "halftone dots relit by a lamp that follows the cursor", {
    background: "#11130F",
    opacity: 0.9,
    grain: 0.02,
    speed: 0.6,
    amplitude: 8,
    trigger: "mousemove",
    radius: 200,
    strength: 0.6,
  }),
  house("hourglass-countdown", "Hourglass Countdown", "Structure", "HourglassDrain", "sand-filled countdown digits draining days hours minutes seconds", {
    opacity: 0.94,
    grain: 0.02,
    speed: 0.5,
    amplitude: 10,
  }),
  house("murmuration", "Murmuration", "Occasional", "MurmurationFlock", "a flock swoops and periodically collapses into the word", {
    background: "#1A2230",
    palette: ["#F7F5F1", "#2F5199", "#93B52F"],
    opacity: 0.9,
    grain: 0.02,
    density: 260,
    speed: 0.7,
    amplitude: 12,
    trigger: "mousemove",
    radius: 130,
    strength: 0.8,
  }),
  house("pendulum-letters", "Pendulum Letters", "Structure", "PendulumSwing", "letters hanging on threads swinging like pendulums", {
    opacity: 0.9,
    grain: 0.02,
    speed: 0.6,
    amplitude: 14,
  }),
  house("favicon-escape", "Tab Escape", "Occasional", "TabEscape", "letters climb out of the word into a mock browser tab, then return", {
    background: "#141a10",
    palette: ["#f4f0e8", "#c8f04a", "#3d4a25"],
    opacity: 0.94,
    grain: 0.02,
    speed: 0.6,
  }),
  house("absence-bloom", "Moss Bloom", "Occasional", "MossBloom", "moss grows over the word over time, then clears and shows how long it grew", {
    background: "#171b12",
    palette: ["#f4f0e8", "#8fc24a", "#3f6b1f", "#c8f04a"],
    opacity: 0.92,
    grain: 0.03,
    speed: 0.5,
  }),
  house("selection-ink", "Ink Pileup", "Occasional", "InkPileup", "collected words fall in as pills and stack up beneath the headline", {
    background: "#11130f",
    palette: ["#3d4a25", "#c8f04a", "#f4f0e8"],
    opacity: 0.92,
    grain: 0.02,
    speed: 0.55,
  }),
];

export function presetById(id: string): MotionPreset {
  return MOTION_PRESETS.find((preset) => preset.id === id) ?? MOTION_PRESETS[0]!;
}

export function matchMotionPreset(phrase: string): string {
  const words = phrase
    .toLowerCase()
    .split(/[^a-z0-9%]+/)
    .filter(Boolean);
  let bestId = "ledger-current";
  let bestScore = 0;

  for (const preset of MOTION_PRESETS) {
    const vibe = (preset.schema.meta?.vibe ?? "").toLowerCase();
    const keywords = VIBE_KEYWORDS[preset.id] ?? [];
    let score = 0;
    for (const word of words) {
      if (keywords.includes(word)) score += 1;
      if (vibe.split(/[^a-z0-9%]+/).includes(word)) score += 1;
    }
    if (score > bestScore) {
      bestScore = score;
      bestId = preset.id;
    }
  }

  return bestId;
}
