import PDFDocument from 'pdfkit';
import type { ProspectWithCompany, Contact, Activity, DueDiligence } from '@shared/schema';

interface CompaniesHouseData {
  officers?: any;
  psc?: any;
  charges?: any;
}

interface PDFSection {
  id: string;
  label: string;
  enabled: boolean;
}

interface PDFLayoutPreferences {
  sections: PDFSection[];
}

interface ProspectReportData {
  prospect: ProspectWithCompany;
  contacts: Contact[];
  activities: Activity[];
  dueDiligence?: DueDiligence;
  companiesHouseData?: CompaniesHouseData | null;
  pdfLayoutPreferences?: PDFLayoutPreferences | null;
}

const headerColor = '#3b82f6';
const textColor = '#1f2937';
const mutedColor = '#6b7280';

const DEFAULT_SECTIONS: PDFSection[] = [
  { id: "companyInfo", label: "Company Information", enabled: true },
  { id: "officers", label: "Officers", enabled: true },
  { id: "psc", label: "Persons with Significant Control", enabled: true },
  { id: "charges", label: "Charges", enabled: true },
  { id: "loanDetails", label: "Loan Details", enabled: true },
  { id: "security", label: "Security & Collateral", enabled: true },
  { id: "notes", label: "Notes", enabled: true },
  { id: "contacts", label: "Key Contacts", enabled: true },
  { id: "activities", label: "Activities & Tasks", enabled: true },
  { id: "dueDiligence", label: "Due Diligence", enabled: true },
];

export function generateProspectReport(data: ProspectReportData): typeof PDFDocument.prototype {
  const doc = new PDFDocument({ size: 'A4', margin: 50 });
  const { prospect, contacts, activities, dueDiligence, companiesHouseData, pdfLayoutPreferences } = data;

  doc.fontSize(24).fillColor(headerColor).text('Prospect Report', { align: 'center' });
  doc.moveDown(0.5);
  doc.fontSize(14).fillColor(mutedColor).text(new Date().toLocaleDateString('en-GB', {
    year: 'numeric',
    month: 'long',
    day: 'numeric'
  }), { align: 'center' });
  doc.moveDown(2);

  const sections = pdfLayoutPreferences?.sections || DEFAULT_SECTIONS;

  sections.forEach((section) => {
    if (!section.enabled) return;

    switch (section.id) {
      case 'companyInfo':
        renderCompanyInfo(doc, prospect);
        break;
      case 'officers':
        if (companiesHouseData?.officers) {
          renderOfficers(doc, companiesHouseData.officers);
        }
        break;
      case 'psc':
        if (companiesHouseData?.psc) {
          renderPSC(doc, companiesHouseData.psc);
        }
        break;
      case 'charges':
        if (companiesHouseData?.charges) {
          renderCharges(doc, companiesHouseData.charges);
        }
        break;
      case 'loanDetails':
        renderLoanDetails(doc, prospect);
        break;
      case 'security':
        renderSecurity(doc, prospect);
        break;
      case 'notes':
        renderNotes(doc, prospect);
        break;
      case 'contacts':
        if (contacts.length > 0) {
          renderContacts(doc, contacts);
        }
        break;
      case 'activities':
        if (activities.length > 0) {
          renderActivities(doc, activities);
        }
        break;
      case 'dueDiligence':
        if (dueDiligence?.data) {
          renderDueDiligence(doc, dueDiligence);
        }
        break;
    }
  });

  doc.fontSize(10).fillColor(mutedColor).text(
    `Generated by FlowLoan on ${new Date().toLocaleString('en-GB')}`,
    50,
    doc.page.height - 50,
    { align: 'center' }
  );

  return doc;
}

function renderCompanyInfo(doc: typeof PDFDocument.prototype, prospect: ProspectWithCompany) {
  doc.fontSize(18).fillColor(headerColor).text('Company Information');
  doc.moveDown(0.5);
  addLine(doc);
  doc.moveDown(0.5);

  doc.fontSize(12).fillColor(textColor);
  addField(doc, 'Company Name:', prospect.company.companyName);
  addField(doc, 'Company Number:', prospect.company.companyNumber);
  if (prospect.company.registeredAddress) {
    addField(doc, 'Registered Address:', prospect.company.registeredAddress);
  }
  if (prospect.company.incorporationDate) {
    addField(doc, 'Incorporation Date:', prospect.company.incorporationDate);
  }
  if (prospect.company.companyStatus) {
    addField(doc, 'Company Status:', prospect.company.companyStatus);
  }
  if (prospect.company.companyType) {
    addField(doc, 'Company Type:', prospect.company.companyType);
  }
  doc.moveDown(2);
}

function renderOfficers(doc: typeof PDFDocument.prototype, officers: any) {
  if (!officers.items || officers.items.length === 0) return;

  doc.fontSize(18).fillColor(headerColor).text('Officers');
  doc.moveDown(0.5);
  addLine(doc);
  doc.moveDown(0.5);
  doc.fontSize(12).fillColor(textColor);

  const activeOfficers = officers.items.filter((o: any) => !o.resigned_on);
  const resignedOfficers = officers.items.filter((o: any) => o.resigned_on);

  if (activeOfficers.length > 0) {
    doc.font('Helvetica-Bold').text(`Active (${activeOfficers.length}):`);
    doc.font('Helvetica').moveDown(0.3);
    activeOfficers.forEach((officer: any) => {
      const name = officer.name || 'Unknown';
      const role = officer.officer_role || 'officer';
      const appointed = officer.appointed_on ? new Date(officer.appointed_on).toLocaleDateString('en-GB') : '';
      doc.text(`• ${name}`, { indent: 10 });
      doc.fontSize(10).fillColor(mutedColor);
      doc.text(`${role.charAt(0).toUpperCase() + role.slice(1)}${appointed ? `, appointed ${appointed}` : ''}`, { indent: 20 });
      doc.fontSize(12).fillColor(textColor);
      doc.moveDown(0.3);
    });
  }

  if (resignedOfficers.length > 0) {
    doc.moveDown(0.3);
    doc.font('Helvetica-Bold').text(`Resigned (${resignedOfficers.length}):`);
    doc.font('Helvetica').moveDown(0.3);
    resignedOfficers.forEach((officer: any) => {
      const name = officer.name || 'Unknown';
      const role = officer.officer_role || 'officer';
      const resigned = officer.resigned_on ? new Date(officer.resigned_on).toLocaleDateString('en-GB') : '';
      doc.text(`• ${name}`, { indent: 10 });
      doc.fontSize(10).fillColor(mutedColor);
      doc.text(`${role.charAt(0).toUpperCase() + role.slice(1)}${resigned ? `, resigned ${resigned}` : ''}`, { indent: 20 });
      doc.fontSize(12).fillColor(textColor);
      doc.moveDown(0.3);
    });
  }
  doc.moveDown(2);
}

function renderPSC(doc: typeof PDFDocument.prototype, psc: any) {
  if (!psc.items || psc.items.length === 0) return;

  doc.fontSize(18).fillColor(headerColor).text('Persons with Significant Control');
  doc.moveDown(0.5);
  addLine(doc);
  doc.moveDown(0.5);
  doc.fontSize(12).fillColor(textColor);

  const activePsc = psc.items.filter((p: any) => !p.ceased_on);
  const ceasedPsc = psc.items.filter((p: any) => p.ceased_on);

  if (activePsc.length > 0) {
    doc.font('Helvetica-Bold').text(`Active (${activePsc.length}):`);
    doc.font('Helvetica').moveDown(0.3);
    activePsc.forEach((psc: any) => {
      const name = psc.name || 'Unknown';
      const kind = psc.kind?.replace(/-/g, ' ') || '';
      doc.text(`• ${name}`, { indent: 10 });
      doc.fontSize(10).fillColor(mutedColor);
      if (kind) doc.text(kind.charAt(0).toUpperCase() + kind.slice(1), { indent: 20 });
      if (psc.natures_of_control && psc.natures_of_control.length > 0) {
        psc.natures_of_control.forEach((nature: string) => {
          const formatted = nature.replace(/-/g, ' ').split(' ').map((w: string) => 
            w.charAt(0).toUpperCase() + w.slice(1).toLowerCase()
          ).join(' ');
          doc.text(`- ${formatted}`, { indent: 20 });
        });
      }
      doc.fontSize(12).fillColor(textColor);
      doc.moveDown(0.3);
    });
  }

  if (ceasedPsc.length > 0) {
    doc.moveDown(0.3);
    doc.font('Helvetica-Bold').text(`Ceased (${ceasedPsc.length}):`);
    doc.font('Helvetica').moveDown(0.3);
    ceasedPsc.forEach((psc: any) => {
      const name = psc.name || 'Unknown';
      const ceased = psc.ceased_on ? new Date(psc.ceased_on).toLocaleDateString('en-GB') : '';
      doc.text(`• ${name}`, { indent: 10 });
      doc.fontSize(10).fillColor(mutedColor);
      if (ceased) doc.text(`Ceased ${ceased}`, { indent: 20 });
      doc.fontSize(12).fillColor(textColor);
      doc.moveDown(0.3);
    });
  }
  doc.moveDown(2);
}

function renderCharges(doc: typeof PDFDocument.prototype, charges: any) {
  if (!charges.items || charges.items.length === 0) return;

  doc.fontSize(18).fillColor(headerColor).text('Charges');
  doc.moveDown(0.5);
  addLine(doc);
  doc.moveDown(0.5);
  doc.fontSize(12).fillColor(textColor);

  const outstandingCharges = charges.items.filter((c: any) => c.status === 'outstanding');
  const satisfiedCharges = charges.items.filter((c: any) => c.status === 'satisfied' || c.status === 'fully-satisfied');

  if (outstandingCharges.length > 0) {
    doc.font('Helvetica-Bold').text(`Outstanding (${outstandingCharges.length}):`);
    doc.font('Helvetica').moveDown(0.3);
    outstandingCharges.forEach((charge: any) => {
      const created = charge.created_on ? new Date(charge.created_on).toLocaleDateString('en-GB') : '';
      const entitled = charge.persons_entitled?.[0]?.name || 'Unknown';
      const type = charge.classification?.description || charge.charge_code || '';
      doc.text(`• ${entitled}`, { indent: 10 });
      doc.fontSize(10).fillColor(mutedColor);
      if (type) doc.text(type, { indent: 20 });
      if (created) doc.text(`Created: ${created}`, { indent: 20 });
      doc.fontSize(12).fillColor(textColor);
      doc.moveDown(0.3);
    });
  }

  if (satisfiedCharges.length > 0) {
    doc.moveDown(0.3);
    doc.font('Helvetica-Bold').text(`Satisfied (${satisfiedCharges.length}):`);
    doc.font('Helvetica').moveDown(0.3);
    satisfiedCharges.forEach((charge: any) => {
      const entitled = charge.persons_entitled?.[0]?.name || 'Unknown';
      const satisfied = charge.satisfied_on ? new Date(charge.satisfied_on).toLocaleDateString('en-GB') : '';
      doc.text(`• ${entitled}`, { indent: 10 });
      doc.fontSize(10).fillColor(mutedColor);
      if (satisfied) doc.text(`Satisfied: ${satisfied}`, { indent: 20 });
      doc.fontSize(12).fillColor(textColor);
      doc.moveDown(0.3);
    });
  }
  doc.moveDown(2);
}

function renderLoanDetails(doc: typeof PDFDocument.prototype, prospect: ProspectWithCompany) {
  doc.fontSize(18).fillColor(headerColor).text('Loan Details');
  doc.moveDown(0.5);
  addLine(doc);
  doc.moveDown(0.5);

  doc.fontSize(12).fillColor(textColor);
  addField(doc, 'Current Stage:', capitalizeStage(prospect.stage));
  if (prospect.loanAmount != null) {
    addField(doc, 'Loan Amount:', formatCurrency(prospect.loanAmount));
  }
  if (prospect.term != null) {
    addField(doc, 'Term:', `${prospect.term} months`);
  }
  if (prospect.interestRate != null) {
    addField(doc, 'Interest Rate:', `${prospect.interestRate}%`);
  }
  if (prospect.priority) {
    addField(doc, 'Priority:', capitalizeStage(prospect.priority));
  }
  doc.moveDown(2);
}

function renderSecurity(doc: typeof PDFDocument.prototype, prospect: ProspectWithCompany) {
  const hasCollateral = (prospect.directorsGuarantee != null && prospect.directorsGuarantee > 0) || 
    (prospect.commercialProperty != null && prospect.commercialProperty > 0) || 
    (prospect.homeEquity != null && prospect.homeEquity > 0) || 
    (prospect.propertyOther != null && prospect.propertyOther > 0) || 
    (prospect.debenture != null && prospect.debenture > 0) || 
    (prospect.parentCompanyGuarantee != null && prospect.parentCompanyGuarantee > 0) || 
    (prospect.collateral != null && prospect.collateral > 0) || 
    (prospect.crossCompanyGuarantee != null && prospect.crossCompanyGuarantee > 0);

  if (!hasCollateral) return;

  doc.fontSize(18).fillColor(headerColor).text('Security & Collateral');
  doc.moveDown(0.5);
  addLine(doc);
  doc.moveDown(0.5);
  doc.fontSize(12).fillColor(textColor);

  if (prospect.directorsGuarantee != null) {
    addField(doc, 'Directors Guarantee:', formatCurrency(prospect.directorsGuarantee));
  }
  if (prospect.commercialProperty != null) {
    addField(doc, 'Commercial Property:', formatCurrency(prospect.commercialProperty));
  }
  if (prospect.homeEquity != null) {
    addField(doc, 'Home Equity:', formatCurrency(prospect.homeEquity));
  }
  if (prospect.propertyOther != null) {
    addField(doc, 'Other Property:', formatCurrency(prospect.propertyOther));
  }
  if (prospect.debenture != null) {
    addField(doc, 'Debenture:', formatCurrency(prospect.debenture));
  }
  if (prospect.parentCompanyGuarantee != null) {
    addField(doc, 'Parent Company Guarantee:', formatCurrency(prospect.parentCompanyGuarantee));
  }
  if (prospect.collateral != null) {
    addField(doc, 'Other Collateral:', formatCurrency(prospect.collateral));
  }
  if (prospect.crossCompanyGuarantee != null) {
    addField(doc, 'Cross Company Guarantee:', formatCurrency(prospect.crossCompanyGuarantee));
  }
  doc.moveDown(2);
}

function renderNotes(doc: typeof PDFDocument.prototype, prospect: ProspectWithCompany) {
  if (!prospect.loanRequirementNotes && !prospect.notes) return;

  doc.fontSize(18).fillColor(headerColor).text('Notes');
  doc.moveDown(0.5);
  addLine(doc);
  doc.moveDown(0.5);
  doc.fontSize(12).fillColor(textColor);
  
  if (prospect.loanRequirementNotes) {
    addField(doc, 'Loan Requirements:', prospect.loanRequirementNotes, true);
  }
  if (prospect.notes) {
    addField(doc, 'Additional Notes:', prospect.notes, true);
  }
  doc.moveDown(2);
}

function renderContacts(doc: typeof PDFDocument.prototype, contacts: Contact[]) {
  doc.fontSize(18).fillColor(headerColor).text('Key Contacts');
  doc.moveDown(0.5);
  addLine(doc);
  doc.moveDown(0.5);
  doc.fontSize(12).fillColor(textColor);

  contacts.forEach((contact, index) => {
    if (index > 0) doc.moveDown(0.5);
    doc.font('Helvetica-Bold').text(contact.name, { continued: contact.isPrimary === 1 });
    if (contact.isPrimary === 1) {
      doc.font('Helvetica').fillColor(headerColor).text(' (Primary)', { continued: false });
      doc.fillColor(textColor);
    } else {
      doc.font('Helvetica');
    }
    if (contact.role) {
      doc.fontSize(10).fillColor(mutedColor).text(`Role: ${contact.role}`);
    }
    if (contact.email) {
      doc.fontSize(10).fillColor(mutedColor).text(`Email: ${contact.email}`);
    }
    if (contact.phone) {
      doc.fontSize(10).fillColor(mutedColor).text(`Phone: ${contact.phone}`);
    }
    doc.fontSize(12).fillColor(textColor);
  });
  doc.moveDown(2);
}

function renderActivities(doc: typeof PDFDocument.prototype, activities: Activity[]) {
  doc.fontSize(18).fillColor(headerColor).text('Activities & Tasks');
  doc.moveDown(0.5);
  addLine(doc);
  doc.moveDown(0.5);
  doc.fontSize(12).fillColor(textColor);

  const pendingActivities = activities.filter(a => a.completed === 0);
  const completedActivities = activities.filter(a => a.completed === 1);

  if (pendingActivities.length > 0) {
    doc.font('Helvetica-Bold').text('Pending Tasks:');
    doc.font('Helvetica').moveDown(0.3);
    pendingActivities.forEach((activity) => {
      doc.text(`• ${activity.title}`, { indent: 10 });
      if (activity.description) {
        doc.fontSize(10).fillColor(mutedColor).text(activity.description, { indent: 20 });
        doc.fontSize(12).fillColor(textColor);
      }
      if (activity.dueDate) {
        doc.fontSize(10).fillColor(mutedColor).text(
          `Due: ${new Date(activity.dueDate).toLocaleDateString('en-GB')}`,
          { indent: 20 }
        );
        doc.fontSize(12).fillColor(textColor);
      }
      doc.moveDown(0.3);
    });
    doc.moveDown(0.5);
  }

  if (completedActivities.length > 0) {
    doc.font('Helvetica-Bold').text('Completed Tasks:');
    doc.font('Helvetica').moveDown(0.3);
    completedActivities.forEach((activity) => {
      doc.text(`✓ ${activity.title}`, { indent: 10 });
      if (activity.description) {
        doc.fontSize(10).fillColor(mutedColor).text(activity.description, { indent: 20 });
        doc.fontSize(12).fillColor(textColor);
      }
      doc.moveDown(0.3);
    });
  }
  doc.moveDown(2);
}

function renderDueDiligence(doc: typeof PDFDocument.prototype, dueDiligence: DueDiligence) {
  const ddData = dueDiligence.data as any;
  
  if (ddData.checklist) {
    doc.fontSize(18).fillColor(headerColor).text('Due Diligence Checklist');
    doc.moveDown(0.5);
    addLine(doc);
    doc.moveDown(0.5);
    doc.fontSize(12).fillColor(textColor);
    
    const totalItems = Object.values(ddData.checklist).flat().length;
    const completedItems = Object.values(ddData.checklist).flat().filter((item: any) => item.checked).length;
    const percentage = totalItems > 0 ? Math.round((completedItems / totalItems) * 100) : 0;
    
    addField(doc, 'Progress:', `${completedItems} of ${totalItems} items (${percentage}%)`);
    doc.moveDown(1);
  }

  if (ddData.loanCalculator) {
    const calc = ddData.loanCalculator;
    if (calc.loanAmount != null && calc.interestRate != null && calc.term != null) {
      doc.fontSize(18).fillColor(headerColor).text('Loan Calculator Results');
      doc.moveDown(0.5);
      addLine(doc);
      doc.moveDown(0.5);
      doc.fontSize(12).fillColor(textColor);
      
      addField(doc, 'Principal:', formatCurrency(calc.loanAmount * 100));
      addField(doc, 'Interest Rate:', `${calc.interestRate}%`);
      addField(doc, 'Term:', `${calc.term} months`);
      if (calc.monthlyPayment != null) {
        addField(doc, 'Monthly Payment:', formatCurrency(calc.monthlyPayment * 100));
      }
      if (calc.totalInterest != null) {
        addField(doc, 'Total Interest:', formatCurrency(calc.totalInterest * 100));
      }
      doc.moveDown(2);
    }
  }

  if (ddData.dscrCalculator) {
    const dscr = ddData.dscrCalculator;
    if (dscr.dscr != null) {
      doc.fontSize(18).fillColor(headerColor).text('DSCR Analysis');
      doc.moveDown(0.5);
      addLine(doc);
      doc.moveDown(0.5);
      doc.fontSize(12).fillColor(textColor);
      
      addField(doc, 'DSCR Ratio:', dscr.dscr.toFixed(2));
      addField(doc, 'Status:', dscr.dscr >= 1.25 ? 'PASS' : dscr.dscr >= 1.0 ? 'WARNING' : 'FAIL');
      doc.moveDown(2);
    }
  }

  if (ddData.financialRatios) {
    const ratios = ddData.financialRatios;
    const hasAnyRatio = ratios.profitMargin != null || ratios.currentRatio != null || 
                        ratios.debtToEquity != null || ratios.returnOnEquity != null || 
                        ratios.assetTurnover != null;
    if (hasAnyRatio) {
      doc.fontSize(18).fillColor(headerColor).text('Financial Ratios');
      doc.moveDown(0.5);
      addLine(doc);
      doc.moveDown(0.5);
      doc.fontSize(12).fillColor(textColor);
      
      if (ratios.profitMargin != null) addField(doc, 'Profit Margin:', `${ratios.profitMargin.toFixed(2)}%`);
      if (ratios.currentRatio != null) addField(doc, 'Current Ratio:', ratios.currentRatio.toFixed(2));
      if (ratios.debtToEquity != null) addField(doc, 'Debt-to-Equity:', ratios.debtToEquity.toFixed(2));
      if (ratios.returnOnEquity != null) addField(doc, 'Return on Equity:', `${ratios.returnOnEquity.toFixed(2)}%`);
      if (ratios.assetTurnover != null) addField(doc, 'Asset Turnover:', ratios.assetTurnover.toFixed(2));
      doc.moveDown(2);
    }
  }
}

function addField(doc: typeof PDFDocument.prototype, label: string, value: string, multiline = false) {
  const labelWidth = 150;
  if (multiline) {
    doc.font('Helvetica-Bold').text(label, { continued: false });
    doc.font('Helvetica').text(value, { indent: 10 });
    doc.moveDown(0.5);
  } else {
    doc.font('Helvetica-Bold').text(label, { continued: true, width: labelWidth });
    doc.font('Helvetica').text(value, { continued: false });
    doc.moveDown(0.3);
  }
}

function addLine(doc: typeof PDFDocument.prototype) {
  doc.strokeColor('#e5e7eb').lineWidth(1).moveTo(50, doc.y).lineTo(doc.page.width - 50, doc.y).stroke();
}

function formatCurrency(amountInPence: number): string {
  return new Intl.NumberFormat('en-GB', {
    style: 'currency',
    currency: 'GBP',
    minimumFractionDigits: 0,
    maximumFractionDigits: 0,
  }).format(amountInPence / 100);
}

function capitalizeStage(stage: string): string {
  return stage
    .split('-')
    .map(word => word.charAt(0).toUpperCase() + word.slice(1))
    .join(' ');
}
